Repository Skyscanner/backpack-android, pull requests merged in 2022-10, with the labels that each got.

#1233 Koa-4921 Created Bpk Fab in Compose
  app/screenshots/default/compose.fab.BpkFabTest_default.png
  app/screenshots/dm/compose.fab.BpkFabTest_default.png
  app/screenshots/rtl/compose.fab.BpkFabTest_default.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/fab/BpkFabTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BpkFabStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ThemeStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/fab/BpkFab.kt
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
  docs/compose/FloatingActionButton/README.md
  docs/compose/FloatingActionButton/screenshots/default.png
  docs/compose/FloatingActionButton/screenshots/default_dm.png
Labels: minor

#1255 Koa-5610 Bumped target SDK to 33
  Backpack/src/main/java/net/skyscanner/backpack/barchart/internal/ChartDrawable.kt
  Backpack/src/main/java/net/skyscanner/backpack/barchart/internal/ChartPopupDrawable.kt
  Backpack/src/main/java/net/skyscanner/backpack/text/BpkTextInputLayout.kt
  android-configuration.gradle
Labels: major

#1258 Improve CI caching
  .github/workflows/_build.yml
  .github/workflows/record_snapshots.yml
Labels: skip-changelog

#1259 Update chip dark mode colour
  Backpack/src/main/res/values-night/backpack.semantic.color.xml
  app/screenshots/dm/chip.BpkChipTest_default.png
  app/screenshots/dm/chip.BpkChipTest_dismiss.png
  app/screenshots/dm/chip.BpkChipTest_onDark.png
  app/screenshots/dm/chip.BpkChipTest_select.png
  app/screenshots/dm/chip.BpkChipTest_withIcon.png
  app/screenshots/dm/chip.BpkChipTest_withIconAndSelect.png
  app/screenshots/dm/compose.chip.BpkChipTest_default.png
  app/screenshots/dm/compose.chip.BpkChipTest_notSelected.png
  app/screenshots/dm/compose.chip.BpkChipTest_notSelected_OnDark.png
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ChipStory.kt
  app/src/main/res/layout/fragment_chip.xml
  app/src/main/res/layout/fragment_chip_with_icon.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/internal/BpkChipColors.kt
  docs/compose/Chip/screenshots/default_dm.png
  docs/view/Chip/screenshots/all_dm.png
  docs/view/Chip/screenshots/on-dark_dm.png
  docs/view/Chip/screenshots/with-icon_dm.png
  docs/view/NavBar/screenshots/collapsed_dm.png
  docs/view/NavBar/screenshots/navigation.png
  docs/view/NavBar/screenshots/navigation_dm.png
  package-lock.json
  package.json
Labels: patch

#1262 KOA-5611 Remove usages of ActivityTestRule
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarControllerTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/presenter/HighlightedDaysAdapterTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/view/NonDrawnDaysOffset.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/view/WeekdayViewHeaderTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/chip/BpkChipTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/starrating/BpkInteractiveStarRatingTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/text/BpkTextInputLayoutTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/text/BpkTextTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/util/TestContext.kt
  app/build.gradle
  app/src/androidTest/java/net/skyscanner/backpack/BpkSnapshotTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/barchart/BpkBarchartTests.kt
  app/src/androidTest/java/net/skyscanner/backpack/calendar/BpkCalendarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/calendar2/BpkCalendarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/dialog/BpkDialogTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/dialog/BpkDialogTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/map/internal/BpkMapMarkerTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/navbar/BpkNavBarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/snackbar/BpkSnackbarTests.kt
  build.gradle
Labels: skip-changelog

#1257 Fixed snapshots generation scripts
  .github/workflows/record_snapshots.yml
  CONTRIBUTING.md
Labels: skip-changelog

#1290 Update surface contrast colour
  Backpack/src/main/res/values-night/backpack.semantic.color.xml
  app/screenshots/dm/button.BpkButtonTest_disabled.LinkOnDark_Standard.png
  app/screenshots/dm/button.BpkButtonTest_disabled.PrimaryOnDark_Standard.png
  app/screenshots/dm/button.BpkButtonTest_disabled.SecondaryOnDark_Standard.png
  app/screenshots/dm/button.BpkButtonTest_loading.LinkOnDark_Standard.png
  app/screenshots/dm/button.BpkButtonTest_loading.PrimaryOnDark_Standard.png
  app/screenshots/dm/button.BpkButtonTest_loading.SecondaryOnDark_Standard.png
  app/screenshots/dm/button.BpkButtonTest_text.LinkOnDark_Standard.png
  app/screenshots/dm/button.BpkButtonTest_text.PrimaryOnDark_Standard.png
  app/screenshots/dm/button.BpkButtonTest_text.SecondaryOnDark_Standard.png
  app/screenshots/dm/compose.button.BpkButtonTest_disabled.LinkOnDark_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_disabled.PrimaryOnDark_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_disabled.SecondaryOnDark_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_loading.LinkOnDark_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_loading.PrimaryOnDark_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_loading.SecondaryOnDark_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_text.LinkOnDark_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_text.PrimaryOnDark_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_text.SecondaryOnDark_Default.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColors.kt
  docs/compose/Button/screenshots/default.png
  docs/compose/Button/screenshots/default_dm.png
  docs/compose/Button/screenshots/large.png
  docs/compose/Button/screenshots/large_dm.png
  docs/compose/Button/screenshots/link.png
  docs/compose/Button/screenshots/link_dm.png
  docs/compose/TextField/screenshots/default.png
  docs/compose/TextField/screenshots/default_dm.png
  docs/compose/TextField/screenshots/disabled.png
  docs/compose/TextField/screenshots/disabled_dm.png
  docs/compose/TextField/screenshots/error.png
  docs/compose/TextField/screenshots/error_dm.png
  docs/compose/TextField/screenshots/validated.png
  docs/compose/TextField/screenshots/validated_dm.png
  docs/view/BottomSheet/screenshots/default_dm.png
  docs/view/Button/screenshots/large.png
  docs/view/Button/screenshots/large_dm.png
  docs/view/Button/screenshots/link.png
  docs/view/Button/screenshots/link_dm.png
  docs/view/Button/screenshots/standard.png
  docs/view/Button/screenshots/standard_dm.png
  docs/view/HorizontalNav/screenshots/default.png
  docs/view/HorizontalNav/screenshots/default_dm.png
  docs/view/Spinner/screenshots/default.png
  docs/view/Spinner/screenshots/default_dm.png
  package-lock.json
  package.json
Labels: patch

#1289 KOA-5619 Add screenshots and badges to readmes
  dangerfile.js
  docs/compose/Badge/README.md
  docs/compose/Button/README.md
  docs/compose/Card/README.md
  docs/compose/Checkbox/README.md
  docs/compose/Chip/README.md
  docs/compose/Dialog/README.md
  docs/compose/FieldSet/README.md
  docs/compose/Flare/README.md
  docs/compose/FloatingActionButton/README.md
  docs/compose/HorizontalNav/README.md
  docs/compose/Icon/README.md
  docs/compose/NavBar/README.md
  docs/compose/Panel/README.md
  docs/compose/RadioButton/README.md
  docs/compose/Skeleton/README.md
  docs/compose/Spinner/README.md
  docs/compose/Switch/README.md
  docs/compose/Text/README.md
  docs/compose/TextField/README.md
  docs/view/Badge/README.md
  docs/view/BarChart/README.md
  docs/view/BottomNav/README.md
  docs/view/BottomSheet/README.md
  docs/view/Button/README.md
  docs/view/Calendar/README.md
  docs/view/Calendar2/README.md
  docs/view/Card/README.md
  docs/view/Checkbox/README.md
  docs/view/Chip/README.md
  docs/view/Dialog/README.md
  docs/view/Flare/README.md
  docs/view/FloatingActionButton/README.md
  docs/view/HorizontalNav/README.md
  docs/view/Icon/README.md
  docs/view/InteractiveStarRating/README.md
  docs/view/InteractiveStarRating/screenshots/default.png
  docs/view/InteractiveStarRating/screenshots/default_dm.png
  docs/view/Maps/README.md
  docs/view/NavBar/README.md
  docs/view/Nudger/README.md
  docs/view/Overlay/README.md
  docs/view/Panel/README.md
  docs/view/RadioButton/README.md
  docs/view/Rating/README.md
  docs/view/Skeleton/README.md
  docs/view/Slider/README.md
  docs/view/Snackbar/README.md
  docs/view/Spinner/README.md
  docs/view/StarRating/README.md
  docs/view/Switch/README.md
  docs/view/Text/README.md
  docs/view/TextField/README.md
  docs/view/TextSpans/README.md
  docs/view/Toast/README.md
Labels: skip-changelog
