Repository Skyscanner/backpack-android, pull requests merged in 2022-07, with the labels that each got.

#1111 Rename spinner sizes to match Figma and other platforms
  app/src/androidTest/java/net/skyscanner/backpack/compose/spinner/BpkSpinnerTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/internal/BpkButtonImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/spinner/BpkSpinner.kt
  docs/compose/Spinner/README.md
Labels: patch

#1114 KOA-5414 Provide list of tokens
  app/build.gradle
  app/src/main/java/net/skyscanner/backpack/demo/data/Tokens.kt
  build.gradle
Labels: skip-changelog

#1117 Migrated Calendar2 to single-threaded model
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/CalendarTestUtils.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/util/TestStateMachine.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/BpkCalendar.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarDispatchers.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarStateMachine.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/list/CalendarAdapter.kt
  app/src/androidTest/java/net/skyscanner/backpack/calendar2/BpkCalendarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
Labels: patch

#1124 Added Compose demo screen for spacing
  app/src/main/java/net/skyscanner/backpack/demo/compose/SpacingStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
Labels: skip-changelog

#1132 [NO JIRA]: Patch del version bump build issue
  gulpfile.js
Labels: skip-changelog

#1129 KOA - 5406 Added a Compose demo screen for radii
  app/src/main/java/net/skyscanner/backpack/demo/compose/RadiiStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/layout/fragment_radii.xml
Labels: skip-changelog

#1133 KOA-5459 Add new colour tokens
  Backpack/src/main/res/values-night/backpack.semantic.color.xml
  Backpack/src/main/res/values/backpack.color.xml
  Backpack/src/main/res/values/backpack.semantic.color.xml
  CONTRIBUTING.md
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColor.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColors.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkColors.kt
  gulpfile.js
  package-lock.json
  package.json
Labels: minor

#1141 KOA-5427 Bump kotlin and compose compiler version
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarRangeSelectionTests.kt
  app/build.gradle
  backpack-compose/build.gradle.kts
  build.gradle
  buildSrc/build.gradle.kts
Labels: dependencies, java
