Repository Skyscanner/backpack-android, pull requests merged in 2022-08, with the labels that each got.

#1152 Added BpkHorizontalNav to Compose
  app/screenshots/default/compose.horizontalnav.BpkHorizontalNavTest_default.png
  app/screenshots/default/compose.horizontalnav.BpkHorizontalNavTest_large.png
  app/screenshots/default/compose.horizontalnav.BpkHorizontalNavTest_largeWithIcon.png
  app/screenshots/default/compose.horizontalnav.BpkHorizontalNavTest_small.png
  app/screenshots/default/compose.horizontalnav.BpkHorizontalNavTest_smallWithIcon.png
  app/screenshots/dm/compose.horizontalnav.BpkHorizontalNavTest_default.png
  app/screenshots/dm/compose.horizontalnav.BpkHorizontalNavTest_largeWithIcon.png
  app/screenshots/dm/compose.horizontalnav.BpkHorizontalNavTest_smallWithIcon.png
  app/screenshots/rtl/compose.horizontalnav.BpkHorizontalNavTest_default.png
  app/screenshots/rtl/compose.horizontalnav.BpkHorizontalNavTest_largeWithIcon.png
  app/screenshots/rtl/compose.horizontalnav.BpkHorizontalNavTest_smallWithIcon.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/horizontalnav/BpkHorizontalNavTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BpkHorizontalNavStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ThemeStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/horizontalnav/BpkHorizontalNav.kt
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
  docs/compose/HorizontalNav/README.md
  docs/compose/HorizontalNav/screenshots/default.png
  docs/compose/HorizontalNav/screenshots/default_dm.png
Labels: minor

#1162 Fix dokka generation
  .github/workflows/release.yml
  buildSrc/build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: skip-changelog

#1156 Koa 5471 group 1 upgrade components to semantic tokens
  Backpack/src/main/java/net/skyscanner/backpack/card/BpkCardView.kt
  Backpack/src/main/res/drawable/border.xml
  Backpack/src/main/res/values-night/backpack.semantic.color.xml
  Backpack/src/main/res/values-night/internal.semantic.color.xml
  Backpack/src/main/res/values/backpack.color.xml
  Backpack/src/main/res/values/internal.semantic.color.xml
  app/screenshots/default/panel.BpkPanelTest_screenshotTestPanelDefault.png
  app/screenshots/default/panel.BpkPanelTest_screenshotTestPanelWithPadding.png
  app/screenshots/default/panel.BpkPanelTest_screenshotTestPanelWithoutPadding.png
  app/screenshots/dm/compose.panel.BpkPanelTest_noPadding.png
  app/screenshots/dm/compose.panel.BpkPanelTest_padded.png
  app/screenshots/dm/panel.BpkPanelTest_screenshotTestPanelDefault.png
  app/screenshots/dm/panel.BpkPanelTest_screenshotTestPanelWithPadding.png
  app/screenshots/dm/panel.BpkPanelTest_screenshotTestPanelWithoutPadding.png
  app/screenshots/rtl/panel.BpkPanelTest_screenshotTestPanelDefault.png
  app/screenshots/rtl/panel.BpkPanelTest_screenshotTestPanelWithPadding.png
  app/screenshots/rtl/panel.BpkPanelTest_screenshotTestPanelWithoutPadding.png
  app/screenshots/themed/panel.BpkPanelTest_screenshotTestPanelDefault.png
  app/screenshots/themed/panel.BpkPanelTest_screenshotTestPanelWithPadding.png
  app/screenshots/themed/panel.BpkPanelTest_screenshotTestPanelWithoutPadding.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/card/BpkCard.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/card/internal/BpkCardImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/panel/BpkPanel.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColor.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkMarcommsColor.kt
  backpack-compose/tokens.gradle.kts
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkColors.kt
  docs/compose/AllIcons/screenshots/default.png
  docs/compose/AllIcons/screenshots/default_dm.png
  docs/compose/Card/screenshots/default.png
  docs/compose/Card/screenshots/default_dm.png
  docs/compose/Panel/screenshots/all_dm.png
  docs/view/Card/screenshots/corner-style-large.png
  docs/view/Card/screenshots/corner-style-large_dm.png
  docs/view/Card/screenshots/default.png
  docs/view/Card/screenshots/default_dm.png
  docs/view/Card/screenshots/selected.png
  docs/view/Card/screenshots/selected_dm.png
  docs/view/Card/screenshots/with-divider-and-corner-style-large.png
  docs/view/Card/screenshots/with-divider-and-corner-style-large_dm.png
  docs/view/Card/screenshots/with-divider-arranged-vertically.png
  docs/view/Card/screenshots/with-divider-arranged-vertically_dm.png
  docs/view/Card/screenshots/with-divider-without-padding.png
  docs/view/Card/screenshots/with-divider-without-padding_dm.png
  docs/view/Card/screenshots/with-divider.png
  docs/view/Card/screenshots/with-divider_dm.png
  docs/view/Card/screenshots/without-padding.png
  docs/view/Card/screenshots/without-padding_dm.png
  docs/view/Panel/screenshots/all.png
  docs/view/Panel/screenshots/all_dm.png
  package-lock.json
  package.json
Labels: patch

#1166 Add props documentation for cards
  docs/view/Card/README.md
Labels: skip-changelog

#1169 Remove new base colours
  Backpack/src/main/res/values-night/backpack.semantic.color.xml
  Backpack/src/main/res/values/backpack.color.xml
  Backpack/src/main/res/values/backpack.semantic.color.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColor.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColors.kt
  backpack-compose/tokens.gradle.kts
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkColors.kt
  gulpfile.js
  package-lock.json
  package.json
Labels: patch

#1170 Migrated BpkMapMarkers to semantic colors
  Backpack/src/main/res/color/bpk_map_marker_content_color.xml
  Backpack/src/main/res/drawable/bpk_map_marker_bg.xml
  Backpack/src/main/res/drawable/bpk_map_marker_pointer.xml
  Backpack/src/main/res/layout/view_bpk_map_marker_label.xml
  Backpack/src/main/res/layout/view_bpk_map_marker_label_with_icon.xml
  app/screenshots/dm/map.internal.BpkMapMarkerTest_screenshotTestMapMarker_Default.png
  app/screenshots/dm/map.internal.BpkMapMarkerTest_screenshotTestMapMarker_Default_NoPointer.png
  app/screenshots/dm/map.internal.BpkMapMarkerTest_screenshotTestMapMarker_Default_Selected.png
  app/screenshots/dm/map.internal.BpkMapMarkerTest_screenshotTestMapMarker_WithIcon.png
  app/screenshots/dm/map.internal.BpkMapMarkerTest_screenshotTestMapMarker_WithIcon_NoPointer.png
  app/screenshots/dm/map.internal.BpkMapMarkerTest_screenshotTestMapMarker_WithIcon_Selected.png
Labels: patch

#1179 Added default action for screenshot recording on the CI
  .github/workflows/record_screenshots.yml
Labels: skip-changelog

#1178 Created tasks for updating the screenshots.
  .github/workflows/record_screenshots.yml
Labels: skip-changelog

#1180 Updated snapshots recording code
  .github/workflows/record_screenshots.yml
Labels: skip-changelog

#1181 Updated snapshots recording code
  .github/workflows/record_screenshots.yml
Labels: skip-changelog

#1184 KOA-5531 Update horizontal nav to new colour tokens
  Backpack/src/main/java/net/skyscanner/backpack/horisontalnav/BpkHorizontalNav.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/horizontalnav/BpkHorizontalNav.kt
Labels: patch

#1186 Breaking the tests.
  .github/workflows/record_snapshots.yml
Labels: skip-changelog

#1187 Breaking the tests
  .github/workflows/record_snapshots.yml
Labels: skip-changelog
