Repository Skyscanner/backpack-android, pull requests merged in 2022-06, with the labels that each got.

#1066 Ensure preview works without wrapping in composable
  app/src/main/java/net/skyscanner/backpack/demo/compose/CardStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/CheckboxStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/DialogStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/PanelStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/RadioButtonStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/SwitchStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/Text.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/TextStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/theme/BpkTheme.kt
Labels: patch

#1075 Lock nvm version to avoid CI failures
  .nvmrc
Labels: skip-changelog

#1077 Fix danger check for compose components
  dangerfile.js
Labels: skip-changelog

#1064 OGM-512 Implement whole month calendar selection
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/CalendarTestUtils.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarCellsLayoutTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarRangeSelectionTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarSelectionTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarSettersTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarSingleSelectionTests.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/BpkCalendar.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/CalendarComponent.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/CalendarEffect.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/CalendarSelection.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarCell.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarCells.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarMonth.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarStateMachine.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/list/CalendarAdapter.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/list/CalendarCellDayHolder.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/list/CalendarCellHeaderHolder.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/view/CalendarDaySelectionBackground.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/view/CalendarDaySelectionContentColor.kt
  Backpack/src/main/res/layout/view_bpk_calendar_header.xml
  app/screenshots/default/calendar2.BpkCalendarTest_screenshotTestCalendarWithWholeMonthButtonEnabled.png
  app/screenshots/default/calendar2.BpkCalendarTest_screenshotTestCalendarWithWholeMonthSetProgrammatically.png
  app/screenshots/dm/calendar2.BpkCalendarTest_screenshotTestCalendarWithWholeMonthButtonEnabled.png
  app/screenshots/dm/calendar2.BpkCalendarTest_screenshotTestCalendarWithWholeMonthSetProgrammatically.png
  app/screenshots/rtl/calendar2.BpkCalendarTest_screenshotTestCalendarWithWholeMonthButtonEnabled.png
  app/screenshots/rtl/calendar2.BpkCalendarTest_screenshotTestCalendarWithWholeMonthSetProgrammatically.png
  app/screenshots/themed/calendar2.BpkCalendarTest_screenshotTestCalendarWithWholeMonthButtonEnabled.png
  app/screenshots/themed/calendar2.BpkCalendarTest_screenshotTestCalendarWithWholeMonthSetProgrammatically.png
  app/src/androidTest/java/net/skyscanner/backpack/calendar2/BpkCalendarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/stories/Calendar2Story.kt
  docs/view/Calendar2/README.md
  docs/view/Calendar2/screenshots/month.png
  docs/view/Calendar2/screenshots/month_dm.png
Labels: major

#1078 Removed deprecated dayOfWeekAccessibilityText and dateAccessibilityText properties from CalendarParams
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
Labels: major

#1076 Add Flare compose component
  app/screenshots/default/compose.flare.BpkFlareTest_contentPadding.png
  app/screenshots/default/compose.flare.BpkFlareTest_default.png
  app/screenshots/default/compose.flare.BpkFlareTest_radius.png
  app/screenshots/default/compose.flare.BpkFlareTest_up.png
  app/screenshots/dm/compose.flare.BpkFlareTest_default.png
  app/screenshots/rtl/compose.flare.BpkFlareTest_default.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/flare/BpkFlareTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/FlareStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/flare/BpkFlare.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/flare/internal/BpkFlareImpl.kt
  docs/compose/Checkbox/README.md
  docs/compose/Flare/README.md
  docs/compose/Flare/screenshots/default.png
  docs/compose/Flare/screenshots/default_dm.png
  docs/view/Flare/screenshots/default.png
  docs/view/Flare/screenshots/default_dm.png
  docs/view/Flare/screenshots/inset-padding.png
  docs/view/Flare/screenshots/inset-padding_dm.png
  docs/view/Flare/screenshots/pointer-offset.png
  docs/view/Flare/screenshots/pointer-offset_dm.png
  docs/view/Flare/screenshots/pointing-up.png
  docs/view/Flare/screenshots/pointing-up_dm.png
  docs/view/Flare/screenshots/rounded.png
  docs/view/Flare/screenshots/rounded_dm.png
Labels: minor

#1084 Fix github actions label exclusion
  .github/release-drafter.yml
Labels: skip-changelog

#1082 Added BpkSpinner component for Compose
  app/screenshots/default/compose.spinner.BpkSpinnerTest_default.png
  app/screenshots/default/compose.spinner.BpkSpinnerTest_disabled.png
  app/screenshots/default/compose.spinner.BpkSpinnerTest_dynamicOnDarkSurface.png
  app/screenshots/default/compose.spinner.BpkSpinnerTest_dynamicTextPrimary.png
  app/screenshots/default/compose.spinner.BpkSpinnerTest_onDarkSurface.png
  app/screenshots/default/compose.spinner.BpkSpinnerTest_small.png
  app/screenshots/default/compose.spinner.BpkSpinnerTest_textPrimary.png
  app/screenshots/dm/compose.button.BpkButtonTest_loading.LinkOnDark_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_loading.LinkOnDark_Large.png
  app/screenshots/dm/compose.button.BpkButtonTest_loading.Link_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_loading.Link_Large.png
  app/screenshots/dm/compose.button.BpkButtonTest_loading.Primary_Default.png
  app/screenshots/dm/compose.button.BpkButtonTest_loading.Primary_Large.png
  app/screenshots/dm/compose.spinner.BpkSpinnerTest_default.png
  app/screenshots/dm/compose.spinner.BpkSpinnerTest_disabled.png
  app/screenshots/dm/compose.spinner.BpkSpinnerTest_onDarkSurface.png
  app/screenshots/dm/compose.spinner.BpkSpinnerTest_textPrimary.png
  app/screenshots/rtl/compose.spinner.BpkSpinnerTest_default.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/spinner/BpkSpinnerTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/SpinnerStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ThemeStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/internal/BpkButtonImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/internal/Colors.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/internal/Size.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/spinner/BpkSpinner.kt
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
  docs/compose/Spinner/README.md
  docs/compose/Spinner/screenshots/default.png
  docs/compose/Spinner/screenshots/default_dm.png
Labels: minor

#1089 Added BpkChip component for Compose
  app/screenshots/default/compose.chip.BpkChipTest_default.png
  app/screenshots/default/compose.chip.BpkChipTest_disabled.png
  app/screenshots/default/compose.chip.BpkChipTest_disabled_OnDark.png
  app/screenshots/default/compose.chip.BpkChipTest_notSelected.png
  app/screenshots/default/compose.chip.BpkChipTest_notSelected_OnDark.png
  app/screenshots/default/compose.chip.BpkChipTest_selected.png
  app/screenshots/default/compose.chip.BpkChipTest_selected_OnDark.png
  app/screenshots/default/compose.chip.BpkChipTest_typeDismiss.png
  app/screenshots/default/compose.chip.BpkChipTest_typeSelected.png
  app/screenshots/default/compose.chip.BpkChipTest_typeSelected_WithIcon.png
  app/screenshots/default/compose.chip.BpkChipTest_withIcon.png
  app/screenshots/dm/compose.chip.BpkChipTest_default.png
  app/screenshots/dm/compose.chip.BpkChipTest_disabled.png
  app/screenshots/dm/compose.chip.BpkChipTest_disabled_OnDark.png
  app/screenshots/dm/compose.chip.BpkChipTest_notSelected.png
  app/screenshots/dm/compose.chip.BpkChipTest_notSelected_OnDark.png
  app/screenshots/dm/compose.chip.BpkChipTest_selected.png
  app/screenshots/dm/compose.chip.BpkChipTest_selected_OnDark.png
  app/screenshots/rtl/compose.chip.BpkChipTest_default.png
  app/screenshots/rtl/compose.chip.BpkChipTest_typeDismiss.png
  app/screenshots/rtl/compose.chip.BpkChipTest_typeSelected.png
  app/screenshots/rtl/compose.chip.BpkChipTest_typeSelected_WithIcon.png
  app/screenshots/rtl/compose.chip.BpkChipTest_withIcon.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/chip/BpkChipTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ChipStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/checkbox/BpkCheckbox.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/chip/BpkChip.kt
  docs/compose/Chip/README.md
  docs/compose/Chip/screenshots/default.png
  docs/compose/Chip/screenshots/default_dm.png
Labels: minor

#1098 Improve contribution guide
  CONTRIBUTING.md
Labels: skip-changelog
