Repository Skyscanner/backpack-android, pull requests merged in 2022-12, with the labels that each got.

#1349 SONIC-1167 Add custom icon to BpkButton-Compose
  app/screenshots/default/compose.button.BpkButtonTest_drawableAtEnd.Primary_Default.png
  app/screenshots/default/compose.button.BpkButtonTest_drawableAtEnd.Primary_Large.png
  app/screenshots/default/compose.button.BpkButtonTest_drawableAtStart.Primary_Default.png
  app/screenshots/default/compose.button.BpkButtonTest_drawableAtStart.Primary_Large.png
  app/screenshots/default/compose.button.BpkButtonTest_iconAtEnd.Primary_Default.png
  app/screenshots/default/compose.button.BpkButtonTest_iconAtEnd.Primary_Large.png
  app/screenshots/rtl/compose.button.BpkButtonTest_drawableAtEnd.Primary_Default.png
  app/screenshots/rtl/compose.button.BpkButtonTest_drawableAtEnd.Primary_Large.png
  app/screenshots/rtl/compose.button.BpkButtonTest_drawableAtStart.Primary_Default.png
  app/screenshots/rtl/compose.button.BpkButtonTest_drawableAtStart.Primary_Large.png
  app/screenshots/rtl/compose.button.BpkButtonTest_iconAtEnd.Primary_Default.png
  app/screenshots/rtl/compose.button.BpkButtonTest_iconAtEnd.Primary_Large.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/button/BpkButtonTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ButtonsStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/drawable-nodpi/button_sample_icon.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/BpkButton.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/internal/BpkButtonImpl.kt
  docs/compose/Button/README.md
  docs/compose/Button/screenshots/drawable-icon.png
  docs/compose/Button/screenshots/drawable-icon_dm.png
Labels: minor

#1346 KOA-4913 Added BpkBarChart for Compose
  .github/workflows/_build.yml
  app/screenshots/default/compose.badge.BpkBadgeTest_brand.png
  app/screenshots/default/compose.barchart.BpkBarchartTest_default.png
  app/screenshots/default/compose.barchart.BpkBarchartTest_fullyFilled.png
  app/screenshots/default/compose.barchart.BpkBarchartTest_halfFilled.png
  app/screenshots/default/compose.barchart.BpkBarchartTest_inactive.png
  app/screenshots/default/compose.barchart.BpkBarchartTest_overfilled.png
  app/screenshots/default/compose.barchart.BpkBarchartTest_selected.png
  app/screenshots/default/compose.barchart.BpkBarchartTest_withLegend.png
  app/screenshots/dm/compose.badge.BpkBadgeTest_brand.png
  app/screenshots/dm/compose.barchart.BpkBarchartTest_default.png
  app/screenshots/dm/compose.barchart.BpkBarchartTest_fullyFilled.png
  app/screenshots/dm/compose.barchart.BpkBarchartTest_inactive.png
  app/screenshots/dm/compose.barchart.BpkBarchartTest_selected.png
  app/screenshots/dm/compose.barchart.BpkBarchartTest_withLegend.png
  app/screenshots/rtl/compose.barchart.BpkBarchartTest_default.png
  app/screenshots/rtl/compose.barchart.BpkBarchartTest_selected.png
  app/screenshots/rtl/compose.barchart.BpkBarchartTest_withLegend.png
  app/src/androidTest/java/net/skyscanner/backpack/BpkSnapshotTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/badge/BpkBadgeTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/barchart/BpkBarchartTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BarChartStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/BpkBarChartData.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/badge/BpkBadge.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/barchart/BpkBarChart.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/barchart/BpkBarChartModel.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/barchart/internal/BarChartBadge.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/barchart/internal/BarChartColumn.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/barchart/internal/BarChartLegend.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/barchart/internal/BarChartList.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/barchart/internal/BarChartTitle.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/flare/internal/BpkFlareImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/FlareShape.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/LazyState.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/Modifier.kt
  docs/compose/Badge/screenshots/default.png
  docs/compose/Badge/screenshots/default_dm.png
  docs/compose/BarChart/README.md
  docs/compose/BarChart/screenshots/default.png
  docs/compose/BarChart/screenshots/default_dm.png
  docs/view/BarChart/README.md
Labels: minor

#1357 Added BpkDivider
  app/screenshots/default/compose.divider.BpkDividerTest_default.png
  app/screenshots/default/compose.divider.BpkDividerTest_withIndent.png
  app/screenshots/dm/compose.divider.BpkDividerTest_default.png
  app/screenshots/dm/compose.divider.BpkDividerTest_withIndent.png
  app/screenshots/rtl/compose.divider.BpkDividerTest_default.png
  app/screenshots/rtl/compose.divider.BpkDividerTest_withIndent.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/divider/BpkDividerTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/Common.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/DividerStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/divider/BpkDivider.kt
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
  docs/compose/Divider/README.md
  docs/compose/Divider/screenshots/default.png
  docs/compose/Divider/screenshots/default_dm.png
Labels: minor

#1355 KOA-5680 Compose-Material is not a transitive dependency anymore
  app/src/androidTest/java/net/skyscanner/backpack/compose/spinner/BpkSpinnerTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BpkSliderStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ChipStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ElevationStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/RadiiStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/SpinnerStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/TextFieldStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ThemeStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  backpack-compose/build.gradle.kts
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/CompositionProviders.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/Swipeable.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkBottomSheet.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkBottomSheetState.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/BpkFloatingNotification.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/internal/BpkFloatingNotificationData.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/slider/BpkSlider.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/theme/BpkTheme.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkShapes.kt
  build.gradle
Labels: major

#1365 SONIC-1227 BpkInventoryDividedCard
  app/screenshots/default/compose.dividedcard.BpkDividedCardTest_cardWidthGreaterThanMinimum.png
  app/screenshots/default/compose.dividedcard.BpkDividedCardTest_cardWidthSmallerThanMinimum.png
  app/screenshots/default/compose.dividedcard.BpkDividedCardTest_emptyCard.png
  app/screenshots/dm/compose.dividedcard.BpkDividedCardTest_cardWidthGreaterThanMinimum.png
  app/screenshots/dm/compose.dividedcard.BpkDividedCardTest_cardWidthSmallerThanMinimum.png
  app/screenshots/dm/compose.dividedcard.BpkDividedCardTest_emptyCard.png
  app/screenshots/rtl/compose.dividedcard.BpkDividedCardTest_cardWidthGreaterThanMinimum.png
  app/screenshots/rtl/compose.dividedcard.BpkDividedCardTest_cardWidthSmallerThanMinimum.png
  app/screenshots/rtl/compose.dividedcard.BpkDividedCardTest_emptyCard.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/dividedcard/BpkDividedCardTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/CardStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/dividedcard/BpkDividedCard.kt
  docs/compose/Card/README.md
  docs/compose/Card/screenshots/default.png
  docs/compose/Card/screenshots/default_dm.png
Labels: minor

#1369 SONIC-1233 BpkPrice
  app/screenshots/default/compose.price.BpkPriceTest_priceFull.Large_End.png
  app/screenshots/default/compose.price.BpkPriceTest_priceFull.Large_Start.png
  app/screenshots/default/compose.price.BpkPriceTest_priceFull.Small_End.png
  app/screenshots/default/compose.price.BpkPriceTest_priceFull.Small_Start.png
  app/screenshots/default/compose.price.BpkPriceTest_priceLineThroughTrailing.Large_End.png
  app/screenshots/default/compose.price.BpkPriceTest_priceLineThroughTrailing.Large_Start.png
  app/screenshots/default/compose.price.BpkPriceTest_priceLineThroughTrailing.Small_End.png
  app/screenshots/default/compose.price.BpkPriceTest_priceLineThroughTrailing.Small_Start.png
  app/screenshots/default/compose.price.BpkPriceTest_priceOnly.Large_End.png
  app/screenshots/default/compose.price.BpkPriceTest_priceOnly.Large_Start.png
  app/screenshots/default/compose.price.BpkPriceTest_priceOnly.Small_End.png
  app/screenshots/default/compose.price.BpkPriceTest_priceOnly.Small_Start.png
  app/screenshots/default/compose.price.BpkPriceTest_priceTrailing.Large_End.png
  app/screenshots/default/compose.price.BpkPriceTest_priceTrailing.Large_Start.png
  app/screenshots/default/compose.price.BpkPriceTest_priceTrailing.Small_End.png
  app/screenshots/default/compose.price.BpkPriceTest_priceTrailing.Small_Start.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceFull.Large_End.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceFull.Large_Start.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceFull.Small_End.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceFull.Small_Start.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceLineThroughTrailing.Large_End.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceLineThroughTrailing.Large_Start.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceLineThroughTrailing.Small_End.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceLineThroughTrailing.Small_Start.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceOnly.Large_End.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceOnly.Large_Start.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceOnly.Small_End.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceOnly.Small_Start.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceTrailing.Large_End.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceTrailing.Large_Start.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceTrailing.Small_End.png
  app/screenshots/dm/compose.price.BpkPriceTest_priceTrailing.Small_Start.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceFull.Large_End.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceFull.Large_Start.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceFull.Small_End.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceFull.Small_Start.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceLineThroughTrailing.Large_End.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceLineThroughTrailing.Large_Start.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceLineThroughTrailing.Small_End.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceLineThroughTrailing.Small_Start.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceOnly.Large_End.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceOnly.Large_Start.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceOnly.Small_End.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceOnly.Small_Start.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceTrailing.Large_End.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceTrailing.Large_Start.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceTrailing.Small_End.png
  app/screenshots/rtl/compose.price.BpkPriceTest_priceTrailing.Small_Start.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/price/BpkPriceTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/PriceStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/BpkPrice.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceImpl.kt
  docs/compose/Price/README.md
  docs/compose/Price/screenshots/large.png
  docs/compose/Price/screenshots/large_dm.png
  docs/compose/Price/screenshots/small.png
  docs/compose/Price/screenshots/small_dm.png
Labels: minor

#1358 Koa-4914 Created BottomNav as Compose
  CONTRIBUTING.md
  app/screenshots/default/compose.bottomnav.BpkBottomNavTest_default.png
  app/screenshots/default/compose.bottomnav.BpkBottomNavTest_selectionUpdated.png
  app/screenshots/dm/compose.bottomnav.BpkBottomNavTest_default.png
  app/screenshots/dm/compose.bottomnav.BpkBottomNavTest_selectionUpdated.png
  app/screenshots/rtl/compose.bottomnav.BpkBottomNavTest_default.png
  app/screenshots/rtl/compose.bottomnav.BpkBottomNavTest_selectionUpdated.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/bottomnav/BpkBottomNavTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/button/BpkButtonTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BpkBottomNavStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ButtonsStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/drawable-nodpi/sample_icon.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomnav/BpkBottomNav.kt
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
  docs/compose/BottomNav/README.md
  docs/compose/BottomNav/screenshots/default.png
  docs/compose/BottomNav/screenshots/default_dm.png
  docs/compose/Slider/README.md
Labels: minor

#1371 Use correct screenshot folder
  templates/component/README.md
Labels: skip-changelog

#1374 Fix error in url
  docs/compose/BottomNav/README.md
Labels: skip-changelog
