Repository Skyscanner/backpack-android, pull requests merged in 2022-11, with the labels that each got.

#1298 Update contributing guide
  CONTRIBUTING.md
Labels: skip-changelog

#1283 Added FloatingNotification for Compose
  CONTRIBUTING.md
  app/screenshots/default/compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/default/compose.floatingnotification.BpkFloatingNotificationTest_withCTA.png
  app/screenshots/default/compose.floatingnotification.BpkFloatingNotificationTest_withIcon.png
  app/screenshots/default/compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCTA.png
  app/screenshots/dm/compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/dm/compose.floatingnotification.BpkFloatingNotificationTest_withCta.png
  app/screenshots/dm/compose.floatingnotification.BpkFloatingNotificationTest_withIcon.png
  app/screenshots/dm/compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  app/screenshots/rtl/compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/rtl/compose.floatingnotification.BpkFloatingNotificationTest_withCta.png
  app/screenshots/rtl/compose.floatingnotification.BpkFloatingNotificationTest_withIcon.png
  app/screenshots/rtl/compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCTA.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/floatingnotification/BpkFloatingNotificationTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/GenerateScreenshots.kt
  app/src/debug/AndroidManifest.xml
  app/src/main/java/net/skyscanner/backpack/demo/compose/FloatingNotificationStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ThemeStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/BpkFloatingNotification.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/internal/BpkFloatingNotification.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/internal/BpkFloatingNotificationData.kt
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
  docs/compose/FloatingNotification/README.md
  docs/compose/FloatingNotification/screenshots/default.png
  docs/compose/FloatingNotification/screenshots/default_dm.png
Labels: minor

#1301 Convert final files to Kotlin
  .idea/fileTemplates/internal/Kotlin Class.kt
  .idea/fileTemplates/internal/Kotlin Enum.kt
  .idea/fileTemplates/internal/Kotlin File.kt
  .idea/fileTemplates/internal/Kotlin Interface.kt
  Backpack/src/main/java/net/skyscanner/backpack/map/internal/BpkMapMarkersTestBridge.kt
  Backpack/src/main/java/net/skyscanner/backpack/toast/BpkToast.java
  Backpack/src/main/java/net/skyscanner/backpack/toast/BpkToast.kt
  android-configuration.gradle
  app/src/androidTest/java/net/skyscanner/backpack/map/internal/BpkMapMarkerTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/stories/InteractiveStarRatingStory.kt
  backpack-compose/build.gradle.kts
Labels: patch

#1295 Added BpkNudger for Compose
  app/screenshots/default/compose.nudger.BpkNudgerTest_default.png
  app/screenshots/default/compose.nudger.BpkNudgerTest_disabled.png
  app/screenshots/default/compose.nudger.BpkNudgerTest_minusDisabled.png
  app/screenshots/default/compose.nudger.BpkNudgerTest_negativeOverflow.png
  app/screenshots/default/compose.nudger.BpkNudgerTest_plusDisabled.png
  app/screenshots/default/compose.nudger.BpkNudgerTest_positiveOverflow.png
  app/screenshots/dm/compose.nudger.BpkNudgerTest_default.png
  app/screenshots/dm/compose.nudger.BpkNudgerTest_disabled.png
  app/screenshots/rtl/compose.nudger.BpkNudgerTest_default.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/nudger/BpkNudgerTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/NudgerStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/layout/fragment_nudger.xml
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/nudger/BpkNudger.kt
  docs/compose/Nudger/README.md
  docs/compose/Nudger/screenshots/all.png
  docs/compose/Nudger/screenshots/all_dm.png
  docs/view/Nudger/screenshots/all.png
  docs/view/Nudger/screenshots/all_dm.png
Labels: minor

#1300 Added BpkRating for Compose
  app/screenshots/default/compose.rating.BpkRatingTest_customContent.png
  app/screenshots/default/compose.rating.BpkRatingTest_default.png
  app/screenshots/default/compose.rating.BpkRatingTest_large.png
  app/screenshots/default/compose.rating.BpkRatingTest_largeCustomContent.png
  app/screenshots/default/compose.rating.BpkRatingTest_largeCustomContentMoSubtitle.png
  app/screenshots/default/compose.rating.BpkRatingTest_largeNoScale.png
  app/screenshots/default/compose.rating.BpkRatingTest_largeTitleOnly.png
  app/screenshots/default/compose.rating.BpkRatingTest_noScale.png
  app/screenshots/default/compose.rating.BpkRatingTest_titleOnly.png
  app/screenshots/dm/compose.rating.BpkRatingTest_default.png
  app/screenshots/dm/compose.rating.BpkRatingTest_large.png
  app/screenshots/rtl/compose.rating.BpkRatingTest_default.png
  app/screenshots/rtl/compose.rating.BpkRatingTest_large.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/rating/BpkRatingTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/RatingStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/rating/BpkRating.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/rating/internal/BpkRatingComponents.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/rating/internal/BpkRatingLayout.kt
  docs/compose/Rating/README.md
  docs/compose/Rating/screenshots/default.png
  docs/compose/Rating/screenshots/default_dm.png
  docs/view/Rating/screenshots/default.png
  docs/view/Rating/screenshots/default_dm.png
  docs/view/Rating/screenshots/pill.png
  docs/view/Rating/screenshots/pill_dm.png
  docs/view/Rating/screenshots/sizes.png
  docs/view/Rating/screenshots/sizes_dm.png
  docs/view/Rating/screenshots/vertical.png
  docs/view/Rating/screenshots/vertical_dm.png
Labels: minor

#1303 Fix CI badge and compose version info
  README.md
Labels: skip-changelog

#1307 Removed notification dot and badge from BpkHorizontalNav
  Backpack/src/main/java/net/skyscanner/backpack/horisontalnav/BpkHorizontalNav.kt
  Backpack/src/main/java/net/skyscanner/backpack/horisontalnav/internal/NotificationDotSpan.kt
  Backpack/src/main/res/layout/view_bpk_tab.xml
  app/screenshots/default/horizontalnav.BpkHorizontalNavTest_screenshotHorizontalNav_badge.png
  app/screenshots/default/horizontalnav.BpkHorizontalNavTest_screenshotHorizontalNav_notificationDot.png
  app/screenshots/dm/horizontalnav.BpkHorizontalNavTest_screenshotHorizontalNav_badge.png
  app/screenshots/dm/horizontalnav.BpkHorizontalNavTest_screenshotHorizontalNav_notificationDot.png
  app/screenshots/rtl/horizontalnav.BpkHorizontalNavTest_screenshotHorizontalNav_badge.png
  app/screenshots/rtl/horizontalnav.BpkHorizontalNavTest_screenshotHorizontalNav_notificationDot.png
  app/screenshots/themed/horizontalnav.BpkHorizontalNavTest_screenshotHorizontalNav_badge.png
  app/screenshots/themed/horizontalnav.BpkHorizontalNavTest_screenshotHorizontalNav_notificationDot.png
  app/src/androidTest/java/net/skyscanner/backpack/horizontalnav/BpkHorizontalNavTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/stories/HorizontalNavStory.kt
  app/src/main/res/layout/fragment_horizontal_nav_default.xml
  docs/view/HorizontalNav/README.md
  docs/view/HorizontalNav/screenshots/default.png
  docs/view/HorizontalNav/screenshots/default_dm.png
Labels: major

#1317 KOA-5673 Update switch track colour
  Backpack/src/main/java/net/skyscanner/backpack/toggle/BpkSwitch.kt
  app/screenshots/default/compose.switch.BpkSwitchTest_customContent.png
  app/screenshots/default/compose.switch.BpkSwitchTest_defaultChecked.png
  app/screenshots/default/compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/default/compose.switch.BpkSwitchTest_disabledChecked.png
  app/screenshots/default/compose.switch.BpkSwitchTest_disabledUnchecked.png
  app/screenshots/default/toggle.BpkSwitchTest_screenshotTestSwitchDefault.png
  app/screenshots/default/toggle.BpkSwitchTest_screenshotTestSwitchDefaultChecked.png
  app/screenshots/dm/compose.switch.BpkSwitchTest_defaultChecked.png
  app/screenshots/dm/compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/dm/compose.switch.BpkSwitchTest_disabledChecked.png
  app/screenshots/dm/compose.switch.BpkSwitchTest_disabledUnchecked.png
  app/screenshots/dm/toggle.BpkSwitchTest_screenshotTestSwitchDefault.png
  app/screenshots/dm/toggle.BpkSwitchTest_screenshotTestSwitchDefaultChecked.png
  app/screenshots/rtl/compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/rtl/toggle.BpkSwitchTest_screenshotTestSwitchDefault.png
  app/screenshots/rtl/toggle.BpkSwitchTest_screenshotTestSwitchDefaultChecked.png
  app/screenshots/themed/toggle.BpkSwitchTest_screenshotTestSwitchDefault.png
  app/screenshots/themed/toggle.BpkSwitchTest_screenshotTestSwitchDefaultChecked.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/switch/BpkSwitch.kt
  docs/compose/Switch/screenshots/default.png
  docs/compose/Switch/screenshots/default_dm.png
  docs/view/Switch/screenshots/default.png
  docs/view/Switch/screenshots/default_dm.png
Labels: patch

#1310 Added BpkBottomSheet for Compose
  app/screenshots/default/bottomsheet.BpkBottomSheetTest_default.png
  app/screenshots/default/compose.bottomsheet.BpkBottomSheetTest_default.png
  app/screenshots/default/compose.bottomsheet.BpkBottomSheetTest_expanded.png
  app/screenshots/dm/bottomsheet.BpkBottomSheetTest_default.png
  app/screenshots/dm/compose.bottomsheet.BpkBottomSheetTest_default.png
  app/screenshots/dm/compose.bottomsheet.BpkBottomSheetTest_expanded.png
  app/screenshots/rtl/bottomsheet.BpkBottomSheetTest_default.png
  app/screenshots/rtl/compose.bottomsheet.BpkBottomSheetTest_default.png
  app/screenshots/rtl/compose.bottomsheet.BpkBottomSheetTest_expanded.png
  app/screenshots/themed/bottomsheet.BpkBottomSheetTest_default.png
  app/src/androidTest/java/net/skyscanner/backpack/bottomsheet/BpkBottomSheetTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/bottomsheet/BpkBottomSheetTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BpkBottomSheetStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/CollapsibleNavigationBarStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/Common.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ComponentUi.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/stories/SubStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkBottomSheet.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkBottomSheetState.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/SwipeableState.kt
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
  docs/compose/BottomSheet/README.md
  docs/compose/BottomSheet/screenshots/default.png
  docs/compose/BottomSheet/screenshots/default_dm.png
  docs/view/BottomSheet/screenshots/default.png
  docs/view/BottomSheet/screenshots/default_dm.png
Labels: minor

#1328 Removed CellStatusStyle.Background from Calendar2
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/list/CalendarCellDayHolder.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/view/CalendarDayStatusBackground.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/view/CalendarDayStatusContentColor.kt
  app/screenshots/default/calendar2.BpkCalendarTest_screenshotTestColoredCalendarDefault.png
  app/screenshots/default/calendar2.BpkCalendarTest_screenshotTestColoredCalendarWithStartAndEndDateSelected.png
  app/screenshots/default/compose.calendar.BpkCalendarTest_colored.png
  app/screenshots/default/compose.calendar.BpkCalendarTest_coloredWithStartAndEndDateSelected.png
  app/screenshots/dm/calendar2.BpkCalendarTest_screenshotTestColoredCalendarDefault.png
  app/screenshots/dm/calendar2.BpkCalendarTest_screenshotTestColoredCalendarWithStartAndEndDateSelected.png
  app/screenshots/dm/compose.calendar.BpkCalendarTest_colored.png
  app/screenshots/dm/compose.calendar.BpkCalendarTest_coloredWithStartAndEndDateSelected.png
  app/screenshots/rtl/calendar2.BpkCalendarTest_screenshotTestColoredCalendarDefault.png
  app/screenshots/rtl/calendar2.BpkCalendarTest_screenshotTestColoredCalendarWithStartAndEndDateSelected.png
  app/screenshots/rtl/compose.calendar.BpkCalendarTest_colored.png
  app/screenshots/rtl/compose.calendar.BpkCalendarTest_coloredWithStartAndEndDateSelected.png
  app/screenshots/themed/calendar2.BpkCalendarTest_screenshotTestColoredCalendarDefault.png
  app/screenshots/themed/calendar2.BpkCalendarTest_screenshotTestColoredCalendarWithStartAndEndDateSelected.png
  app/src/androidTest/java/net/skyscanner/backpack/calendar2/BpkCalendarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/calendar2/BpkCalendarTestCases.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/CalendarStoryType.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarInfoTests.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
  docs/compose/Calendar2/README.md
  docs/compose/Calendar2/screenshots/colored.png
  docs/compose/Calendar2/screenshots/colored_dm.png
  docs/view/Calendar2/README.md
  docs/view/Calendar2/screenshots/colored.png
  docs/view/Calendar2/screenshots/colored_dm.png
Labels: major

#1324 SONIC-1132 BpkImageDialog
  app/screenshots/default/compose.dialog.BpkDialogTest_imageEndAlignment.png
  app/screenshots/default/compose.dialog.BpkDialogTest_imageStartAlignment.png
  app/screenshots/dm/compose.dialog.BpkDialogTest_imageEndAlignment.png
  app/screenshots/dm/compose.dialog.BpkDialogTest_imageStartAlignment.png
  app/screenshots/rtl/compose.dialog.BpkDialogTest_imageEndAlignment.png
  app/screenshots/rtl/compose.dialog.BpkDialogTest_imageStartAlignment.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/dialog/BpkDialogTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/DialogStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/dialog/BpkDialog.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/dialog/internal/BpkDialogImpl.kt
  docs/compose/Dialog/README.md
  docs/compose/Dialog/screenshots/flare.png
  docs/compose/Dialog/screenshots/flare_dm.png
  docs/compose/Dialog/screenshots/image-end-alignment.png
  docs/compose/Dialog/screenshots/image-end-alignment_dm.png
  docs/compose/Dialog/screenshots/image-start-alignment.png
  docs/compose/Dialog/screenshots/image-start-alignment_dm.png
Labels: minor

#1316 Koa-4929 Created BpkSlider as Compose
  app/screenshots/default/compose.slider.BpkSliderTest_default.png
  app/screenshots/default/compose.slider.BpkSliderTest_range.png
  app/screenshots/dm/compose.slider.BpkSliderTest_default.png
  app/screenshots/dm/compose.slider.BpkSliderTest_range.png
  app/screenshots/rtl/compose.slider.BpkSliderTest_default.png
  app/screenshots/rtl/compose.slider.BpkSliderTest_range.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/slider/BpkSliderTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BpkSliderStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ThemeStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/slider/BpkSlider.kt
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
  docs/compose/Slider/README.md
  docs/compose/Slider/screenshots/default.png
  docs/compose/Slider/screenshots/default_dm.png
Labels: minor

#1335 Fix yml formatting
  .github/workflows/record_snapshots.yml
Labels: skip-changelog

#1336 KOA-5679 Include kotlin sourceset when publishing
  gradle-maven-push.gradle
Labels: patch

#1308 Create script for setting up new components
  CONTRIBUTING.md
  docs/compose/Slider/README.md
  scripts/generate-component.py
  templates/component/Component.kt
  templates/component/README.md
  templates/component/Story.kt
  templates/component/Test.kt
Labels: skip-changelog

#1342 Move recording snapshots to commit trigger
  .github/workflows/_build.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/record_snapshots.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
Labels: skip-changelog
