Repository Skyscanner/backpack-android, pull requests merged in 2022-05, with the labels that each got.

#1006 Exclude js and github actions from changelog
  .github/release-drafter.yml
  .github/workflows/pr.yml
Labels: skip-changelog

#1005 Improved Calendar2 accessibility.
  Backpack/build.gradle
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/CalendarTestUtils.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarCellsLayoutTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarInfoTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarLocalisationTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarRangeSelectionTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarSelectionTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarSettersTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarSingleSelectionTests.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/util/StateMachineTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/util/TestStateMachine.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/BpkCalendar.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarCell.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/list/CalendarCellDayHolder.kt
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/view/CalendarHeaderView.kt
  Backpack/src/main/res/layout/view_bpk_calendar_header.xml
Labels: patch

#1009 Added CI secure enviroment
  .github/workflows/release.yml
  .gitignore
Labels: skip-changelog

#1016 KOA-5047 Remove BpkButtonLink
  .spelling
  Backpack/src/androidTest/java/net/skyscanner/backpack/button/BpkButtonLinkTest.kt
  Backpack/src/main/java/net/skyscanner/backpack/button/BpkButtonLink.kt
  Backpack/src/main/res/values/attrs.xml
  app/screenshots/default/button.BpkButtonLinkTest_disabled.Standard.png
  app/screenshots/default/button.BpkButtonLinkTest_iconAtEnd.Large.png
  app/screenshots/default/button.BpkButtonLinkTest_iconAtEnd.Standard.png
  app/screenshots/default/button.BpkButtonLinkTest_iconAtStart.Large.png
  app/screenshots/default/button.BpkButtonLinkTest_iconAtStart.Standard.png
  app/screenshots/default/button.BpkButtonLinkTest_noUppercase.Large.png
  app/screenshots/default/button.BpkButtonLinkTest_noUppercase.Standard.png
  app/screenshots/default/button.BpkButtonLinkTest_text.Large.png
  app/screenshots/default/button.BpkButtonLinkTest_text.Standard.png
  app/screenshots/dm/button.BpkButtonLinkTest_disabled.Standard.png
  app/screenshots/dm/button.BpkButtonLinkTest_text.Large.png
  app/screenshots/dm/button.BpkButtonLinkTest_text.Standard.png
  app/screenshots/rtl/button.BpkButtonLinkTest_iconAtEnd.Large.png
  app/screenshots/rtl/button.BpkButtonLinkTest_iconAtEnd.Standard.png
  app/screenshots/rtl/button.BpkButtonLinkTest_iconAtStart.Large.png
  app/screenshots/rtl/button.BpkButtonLinkTest_iconAtStart.Standard.png
  app/src/androidTest/java/net/skyscanner/backpack/button/BpkButtonLinkTest.kt
Labels: major

#1019 KOA-4973 Move release process to CI
  .github/workflows/release.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
  publish-root.gradle
  release.js
Labels: skip-changelog

#1023 KOA-4973 Set publishing environment in release job
  .github/workflows/release.yml
Labels: skip-changelog

#1025 KOA-4974 Move apk build before publishing
  .github/workflows/release.yml
Labels: skip-changelog

#1033 KOA-4927 Tweak compose RadioButton API and improve accessibility
  app/screenshots/default/compose.radiobutton.BpkRadioButtonTest_customContent.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/radiobutton/BpkRadioButtonTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/RadioButtonStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ThemeStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/radiobutton/BpkRadioButton.kt
  docs/compose/RadioButton/screenshots/default.png
  docs/compose/RadioButton/screenshots/default_dm.png
Labels: patch

#1032 KOA-4933 Create compose BpkSwitch component
  app/screenshots/default/compose.switch.BpkSwitchTest_customContent.png
  app/screenshots/default/compose.switch.BpkSwitchTest_defaultChecked.png
  app/screenshots/default/compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/default/compose.switch.BpkSwitchTest_disabledChecked.png
  app/screenshots/default/compose.switch.BpkSwitchTest_disabledUnchecked.png
  app/screenshots/dm/compose.switch.BpkSwitchTest_defaultChecked.png
  app/screenshots/dm/compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/dm/compose.switch.BpkSwitchTest_disabledChecked.png
  app/screenshots/dm/compose.switch.BpkSwitchTest_disabledUnchecked.png
  app/screenshots/rtl/compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/switch/BpkSwitchTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/SwitchStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ThemeStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/layout/fragment_switch.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/switch/BpkSwitch.kt
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
  docs/compose/Switch/README.md
  docs/compose/Switch/screenshots/default.png
  docs/compose/Switch/screenshots/default_dm.png
  docs/view/Switch/screenshots/default.png
  docs/view/Switch/screenshots/default_dm.png
Labels: minor

#1034 Tweak CI permissions for build steps
  .github/workflows/_build.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: skip-changelog

#1036 KOA-4927 Use correct selectable modifier for BpkRadioButton
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/radiobutton/BpkRadioButton.kt
Labels: patch

#1037 KOA-4933 Update view switch size to match compose
  Backpack/src/main/res/values/dimens.xml
  app/screenshots/default/toggle.BpkSwitchTest_screenshotTestSwitchDefault.png
  app/screenshots/default/toggle.BpkSwitchTest_screenshotTestSwitchDefaultChecked.png
  app/screenshots/dm/toggle.BpkSwitchTest_screenshotTestSwitchDefault.png
  app/screenshots/dm/toggle.BpkSwitchTest_screenshotTestSwitchDefaultChecked.png
  app/screenshots/rtl/toggle.BpkSwitchTest_screenshotTestSwitchDefault.png
  app/screenshots/rtl/toggle.BpkSwitchTest_screenshotTestSwitchDefaultChecked.png
  app/screenshots/themed/toggle.BpkSwitchTest_screenshotTestSwitchDefault.png
  app/screenshots/themed/toggle.BpkSwitchTest_screenshotTestSwitchDefaultChecked.png
  docs/view/Switch/screenshots/default.png
  docs/view/Switch/screenshots/default_dm.png
Labels: patch

#1039 Added BpkPanel
  app/screenshots/default/compose.panel.BpkPanelTest_noPadding.png
  app/screenshots/default/compose.panel.BpkPanelTest_padded.png
  app/screenshots/dm/compose.panel.BpkPanelTest_noPadding.png
  app/screenshots/dm/compose.panel.BpkPanelTest_padded.png
  app/screenshots/rtl/compose.panel.BpkPanelTest_padded.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/panel/BpkPanelTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/PanelStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/panel/BpkPanel.kt
  docs/compose/Panel/README.md
  docs/compose/Panel/screenshots/all.png
  docs/compose/Panel/screenshots/all_dm.png
Labels: I WIP my hair back and forth, minor

#1045 Update sd card creation guide
  CONTRIBUTING.md
Labels: skip-changelog

#1046 Don't use MainActivity for screenshot tests
  app/screenshots/default/calendar2.BpkCalendarTest_screenshotTestCalendarWithSingleDaySelected.png
  app/screenshots/default/calendar2.BpkCalendarTest_screenshotTestCalendarWithStartAndEndDateSelected.png
  app/screenshots/default/calendar2.BpkCalendarTest_screenshotTestColoredCalendarWithStartAndEndDateSelected.png
  app/screenshots/dm/calendar2.BpkCalendarTest_screenshotTestCalendarWithSingleDaySelected.png
  app/screenshots/dm/calendar2.BpkCalendarTest_screenshotTestCalendarWithStartAndEndDateSelected.png
  app/screenshots/dm/calendar2.BpkCalendarTest_screenshotTestColoredCalendarWithStartAndEndDateSelected.png
  app/screenshots/rtl/calendar2.BpkCalendarTest_screenshotTestCalendarWithSingleDaySelected.png
  app/screenshots/rtl/calendar2.BpkCalendarTest_screenshotTestCalendarWithStartAndEndDateSelected.png
  app/screenshots/rtl/calendar2.BpkCalendarTest_screenshotTestColoredCalendarWithStartAndEndDateSelected.png
  app/screenshots/themed/calendar2.BpkCalendarTest_screenshotTestCalendarWithSingleDaySelected.png
  app/screenshots/themed/calendar2.BpkCalendarTest_screenshotTestCalendarWithStartAndEndDateSelected.png
  app/screenshots/themed/calendar2.BpkCalendarTest_screenshotTestColoredCalendarWithStartAndEndDateSelected.png
  app/screenshots/themed/snackbar.BpkSnackbarTests_screenshotTestSnackbar_DefaultWithAction.png
  app/screenshots/themed/snackbar.BpkSnackbarTests_screenshotTestSnackbar_withIcon.png
  app/screenshots/themed/snackbar.BpkSnackbarTests_screenshotTestSnackbar_withTitle.png
  app/screenshots/themed/snackbar.BpkSnackbarTests_screenshotTestSnackbar_withTitleAndIcon.png
  app/src/androidTest/java/net/skyscanner/backpack/BpkSnapshotTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/calendar/BpkCalendarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/calendar2/BpkCalendarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/snackbar/BpkSnackbarTests.kt
Labels: skip-changelog

#1043 KOA-4919 Add compose BpkDialog
  app/build.gradle
  app/screenshots/default/compose.dialog.BpkDialogTest_destructive.png
  app/screenshots/default/compose.dialog.BpkDialogTest_noIcon.png
  app/screenshots/default/compose.dialog.BpkDialogTest_successOneButton.png
  app/screenshots/default/compose.dialog.BpkDialogTest_successThreeButtons.png
  app/screenshots/default/compose.dialog.BpkDialogTest_successTwoButtons.png
  app/screenshots/default/compose.dialog.BpkDialogTest_warning.png
  app/screenshots/dm/compose.dialog.BpkDialogTest_destructive.png
  app/screenshots/dm/compose.dialog.BpkDialogTest_noIcon.png
  app/screenshots/dm/compose.dialog.BpkDialogTest_successOneButton.png
  app/screenshots/dm/compose.dialog.BpkDialogTest_successThreeButtons.png
  app/screenshots/dm/compose.dialog.BpkDialogTest_successTwoButtons.png
  app/screenshots/dm/compose.dialog.BpkDialogTest_warning.png
  app/screenshots/rtl/compose.dialog.BpkDialogTest_successOneButton.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/dialog/BpkDialogTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/GenerateScreenshots.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/DialogStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/dialog/BpkDialog.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/dialog/internal/BpkDialogImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/dialog/internal/Types.kt
  docs/compose/Dialog/README.md
  docs/compose/Dialog/screenshots/destructive.png
  docs/compose/Dialog/screenshots/destructive_dm.png
  docs/compose/Dialog/screenshots/success.png
  docs/compose/Dialog/screenshots/success_dm.png
  docs/compose/Dialog/screenshots/warning.png
  docs/compose/Dialog/screenshots/warning_dm.png
Labels: minor

#1052 KOA-5128 Update compose card focused property to enum
  app/screenshots/default/compose.card.BpkCardTest_focused.png
  app/screenshots/default/compose.card.BpkCardTest_noPadding.png
  app/screenshots/default/compose.card.BpkCardTest_unfocused.png
  app/screenshots/dm/compose.card.BpkCardTest_focused.png
  app/screenshots/dm/compose.card.BpkCardTest_unfocused.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/card/BpkCardTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/CardStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/card/BpkCard.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/card/internal/BpkCardImpl.kt
  docs/compose/Card/README.md
  docs/compose/Card/screenshots/default.png
  docs/compose/Card/screenshots/default_dm.png
Labels: major

#1056 Add guide for getting push rights
  CONTRIBUTING.md
Labels: skip-changelog

#1058 Update guide for deploying branches/locally
  CONTRIBUTING.md
Labels: skip-changelog

#1059 Simplify dialog test code
  app/src/androidTest/java/net/skyscanner/backpack/compose/dialog/BpkDialogTest.kt
Labels: skip-changelog

#1063 KOA-5106 Update checkbox & radiobuttion paddings
  Backpack/src/main/java/net/skyscanner/backpack/checkbox/BpkCheckbox.kt
  Backpack/src/main/java/net/skyscanner/backpack/radiobutton/BpkRadioButton.kt
  app/screenshots/default/checkbox.BpkCheckboxTests_screenshotTestCheckbox_Checked.png
  app/screenshots/default/checkbox.BpkCheckboxTests_screenshotTestCheckbox_CheckedDisabled.png
  app/screenshots/default/checkbox.BpkCheckboxTests_screenshotTestCheckbox_Default.png
  app/screenshots/default/checkbox.BpkCheckboxTests_screenshotTestCheckbox_Disabled.png
  app/screenshots/default/compose.checkbox.BpkCheckboxTest_checked.png
  app/screenshots/default/compose.checkbox.BpkCheckboxTest_customContent.png
  app/screenshots/default/compose.checkbox.BpkCheckboxTest_default.png
  app/screenshots/default/compose.checkbox.BpkCheckboxTest_disabledChecked.png
  app/screenshots/default/compose.checkbox.BpkCheckboxTest_disabledUnchecked.png
  app/screenshots/default/compose.checkbox.BpkCheckboxTest_intermediate.png
  app/screenshots/default/compose.checkbox.BpkCheckboxTest_unchecked.png
  app/screenshots/default/compose.radiobutton.BpkRadioButtonTest_customContent.png
  app/screenshots/default/compose.radiobutton.BpkRadioButtonTest_defaultChecked.png
  app/screenshots/default/compose.radiobutton.BpkRadioButtonTest_defaultUnchecked.png
  app/screenshots/default/compose.radiobutton.BpkRadioButtonTest_disabledChecked.png
  app/screenshots/default/compose.radiobutton.BpkRadioButtonTest_disabledUnchecked.png
  app/screenshots/default/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_Checked.png
  app/screenshots/default/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_CheckedDisabled.png
  app/screenshots/default/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_Default.png
  app/screenshots/default/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_Disabled.png
  app/screenshots/dm/checkbox.BpkCheckboxTests_screenshotTestCheckbox_Checked.png
  app/screenshots/dm/checkbox.BpkCheckboxTests_screenshotTestCheckbox_CheckedDisabled.png
  app/screenshots/dm/checkbox.BpkCheckboxTests_screenshotTestCheckbox_Default.png
  app/screenshots/dm/checkbox.BpkCheckboxTests_screenshotTestCheckbox_Disabled.png
  app/screenshots/dm/compose.checkbox.BpkCheckboxTest_checked.png
  app/screenshots/dm/compose.checkbox.BpkCheckboxTest_default.png
  app/screenshots/dm/compose.checkbox.BpkCheckboxTest_disabledChecked.png
  app/screenshots/dm/compose.checkbox.BpkCheckboxTest_disabledUnchecked.png
  app/screenshots/dm/compose.checkbox.BpkCheckboxTest_intermediate.png
  app/screenshots/dm/compose.checkbox.BpkCheckboxTest_unchecked.png
  app/screenshots/dm/compose.radiobutton.BpkRadioButtonTest_defaultChecked.png
  app/screenshots/dm/compose.radiobutton.BpkRadioButtonTest_defaultUnchecked.png
  app/screenshots/dm/compose.radiobutton.BpkRadioButtonTest_disabledChecked.png
  app/screenshots/dm/compose.radiobutton.BpkRadioButtonTest_disabledUnchecked.png
  app/screenshots/dm/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_Checked.png
  app/screenshots/dm/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_CheckedDisabled.png
  app/screenshots/dm/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_Default.png
  app/screenshots/dm/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_Disabled.png
  app/screenshots/rtl/compose.checkbox.BpkCheckboxTest_default.png
  app/screenshots/rtl/compose.radiobutton.BpkRadioButtonTest_defaultUnchecked.png
  app/screenshots/themed/checkbox.BpkCheckboxTests_screenshotTestCheckbox_Checked.png
  app/screenshots/themed/checkbox.BpkCheckboxTests_screenshotTestCheckbox_CheckedDisabled.png
  app/screenshots/themed/checkbox.BpkCheckboxTests_screenshotTestCheckbox_Default.png
  app/screenshots/themed/checkbox.BpkCheckboxTests_screenshotTestCheckbox_Disabled.png
  app/screenshots/themed/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_Checked.png
  app/screenshots/themed/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_CheckedDisabled.png
  app/screenshots/themed/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_Default.png
  app/screenshots/themed/radiobutton.BpkRadioButtonTests_screenshotTestRadioButton_Disabled.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/checkbox/BpkCheckbox.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/radiobutton/BpkRadioButton.kt
  docs/compose/Checkbox/screenshots/default.png
  docs/compose/Checkbox/screenshots/default_dm.png
  docs/compose/RadioButton/screenshots/default.png
  docs/compose/RadioButton/screenshots/default_dm.png
  docs/view/Checkbox/screenshots/default.png
  docs/view/Checkbox/screenshots/default_dm.png
  docs/view/RadioButton/screenshots/default.png
  docs/view/RadioButton/screenshots/default_dm.png
Labels: patch

#1065 Skip signing task for snapshot versions
  gradle-maven-push.gradle
Labels: skip-changelog
