Repository Skyscanner/backpack-android, pull requests merged in 2023-09, with the labels that each got.

#1705 Koa-6261 Update Explore icon for Android
  Backpack/src/main/res/values-night/backpack.internal.color.xml
  Backpack/src/main/res/values/backpack.internal.color.xml
  app/screenshots/oss/debug/default/net.skyscanner.backpack.icon.BpkIconTest_large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.icon.BpkIconTest_small.png
  backpack-common/src/main/res/drawable-nodpi/bpk_explore.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_explore_sm.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPriceMapMarker.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/internal/BpkMapMarkerColors.kt
  docs/compose/Icon/screenshots/default.png
  docs/compose/Icon/screenshots/default_dm.png
  docs/view/Icon/screenshots/default.png
  docs/view/Icon/screenshots/default_dm.png
  docs/view/Icon/screenshots/small.png
  docs/view/Icon/screenshots/small_dm.png
  package-lock.json
  package.json
Labels: patch

#1717 Tweaks to bpkModal and BpkMapPriceMarker
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPriceMapMarker.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/modal/BpkModal.kt
Labels: minor

#1719 Fixed the KSP not generating the info due to the bug
  gradle.properties
Labels: skip-changelog

#1720 Change modal to a dialog
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.modal.BpkModalTest_modalDefault.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.modal.BpkModalTest_modalWithBackIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.modal.BpkModalTest_modalWithoutAction.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.modal.BpkModalTest_modalWithoutActionAndTitle.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.modal.BpkModalTest_modalDefault.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.modal.BpkModalTest_modalWithBackIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.modal.BpkModalTest_modalWithoutAction.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.modal.BpkModalTest_modalWithoutActionAndTitle.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.modal.BpkModalTest_modalDefault.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.modal.BpkModalTest_modalWithBackIcon.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.modal.BpkModalTest_modalWithoutAction.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.modal.BpkModalTest_modalWithoutActionAndTitle.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/modal/BpkModalTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/modal/BpkModal.kt
Labels: patch

#1708 Added Nudger with title, subtitle and icon
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.nudger.BpkNudgerTest_defaultRow.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.nudger.BpkNudgerTest_withIconNoSubtitle.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.nudger.BpkNudgerTest_withNoIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.nudger.BpkNudgerTest_withNoSubtitle.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.nudger.BpkNudgerTest_defaultRow.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.nudger.BpkNudgerTest_defaultRow.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/nudger/BpkNudgerTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/NudgerStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/nudger/BpkNudger.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/Modifier.kt
  docs/compose/Nudger/README.md
  docs/compose/Nudger/screenshots/default.png
  docs/compose/Nudger/screenshots/default_dm.png
Labels: minor

#1726 Fix select item text style
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlist.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlist.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlist.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/select/internal/BpkSelectImpl.kt
Labels: patch

#1718 Koa-6266 Bumped to Compose 1.5 & target SDK 34
  Backpack/src/main/java/net/skyscanner/backpack/skeleton/BpkCircleSkeleton.kt
  Backpack/src/main/java/net/skyscanner/backpack/skeleton/BpkHeadlineSkeleton.kt
  android-configuration.gradle
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/barchart/internal/BarChartTitle.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/carousel/BpkCarousel.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/carousel/BpkCarouselState.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/internal/BpkFloatingNotification.kt
  gradle/libs.versions.toml
Labels: major

#1728 Disabled the custom font of BpkBottomNav for RTL locales
  Backpack/src/main/java/net/skyscanner/backpack/bottomnav/BpkBottomNav.kt
Labels: patch

#1731 Allow consuming of Marker onClick behaviour and set default focused zIndex
  app/src/main/java/net/skyscanner/backpack/demo/compose/MapStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkIconMapMarker.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPriceMapMarker.kt
Labels: major

#1738 OGM-1968 Update month selection to only select days in calendar range
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarRangeSelectionTests.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarSelection.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarStateMachine.kt
Labels: minor
