Repository Skyscanner/backpack-android, pull requests merged in 2023-04, with the labels that each got.

#1536 Fixed BpkCarousel scrolling behaviour
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/carousel/BpkCarousel.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/carousel/BpkCarouselState.kt
Labels: patch

#1544 KOA-6018 Migrate non broken components to MD3 – Compose
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.button.BpkButtonTest_loading.LinkOnDark_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_loading.LinkOnDark_Default.png
  backpack-compose/build.gradle
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/internal/BpkButtonImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/dialog/internal/BpkDialogImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/fab/BpkFab.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/internal/BpkFloatingNotification.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/icon/BpkIcon.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/rating/internal/BpkRatingComponents.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/spinner/BpkSpinner.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/text/BpkText.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/theme/BpkTheme.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/CompositionProviders.kt
  gradle/libs.versions.toml
Labels: patch

#1547 Migrated BpkDivider to MD3
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.divider.BpkDividerTest_withIndent.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.divider.BpkDividerTest_withIndent.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.divider.BpkDividerTest_withIndent.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/divider/BpkDividerTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/DividerStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/divider/BpkDivider.kt
  docs/compose/Divider/screenshots/default.png
  docs/compose/Divider/screenshots/default_dm.png
Labels: major

#1557 [KOA-5970] Add experimentation guidelines
  CONTRIBUTING.md
Labels: skip-changelog

#1558 Update readme
  docs/compose/Price/README.md
Labels: skip-changelog

#1559 KOA-6008 Migrate bottom nav to custom implementation – Compose
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.bottomnav.BpkBottomNavTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.bottomnav.BpkBottomNavTest_selectionUpdated.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.bottomnav.BpkBottomNavTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.bottomnav.BpkBottomNavTest_default.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomnav/BpkBottomNav.kt
Labels: minor

#1562 Moved :meta-processor to :meta:processor
  app/build.gradle
  meta/processor/build.gradle
  meta/processor/src/main/kotlin/net/skyscanner/backpack/ksp/Annotations.kt
  meta/processor/src/main/kotlin/net/skyscanner/backpack/ksp/BackpackSymbolProcessor.kt
  meta/processor/src/main/kotlin/net/skyscanner/backpack/ksp/Extensions.kt
  meta/processor/src/main/kotlin/net/skyscanner/backpack/ksp/Models.kt
  meta/processor/src/main/kotlin/net/skyscanner/backpack/ksp/References.kt
  meta/processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/AbstractStoriesVisitor.kt
  meta/processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ComponentsVisitor.kt
  meta/processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ComposeStoriesVisitor.kt
  meta/processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ViewStoriesVisitor.kt
  meta/processor/src/main/kotlin/net/skyscanner/backpack/ksp/writer/StoriesWriter.kt
  meta/processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
  settings.gradle
Labels: skip-changelog

#1569 KOA-6068 Add option to find icon by name
  .idea/inspectionProfiles/ktlint.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/icon/BpkIcon.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkIcon.kt
  backpack-compose/src/test/kotlin/net/skyscanner/backpack/compose/icon/BpkIconTest.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkIcons.kt
  docs/compose/Icon/README.md
Labels: minor

#1571 SONIC-1568: View Dialog Corrections
  Backpack/src/main/java/net/skyscanner/backpack/dialog/BpkDialog.kt
  Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/AlertDialogImpl.kt
  Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/BpkDialogImpl.kt
  Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/FlareDialogImpl.kt
  Backpack/src/main/res/layout/bpk_dialog.xml
  Backpack/src/main/res/layout/bpk_dialog_flare.xml
  Backpack/src/main/res/values-large/dimens.xml
  Backpack/src/main/res/values-sw600dp/dimens.xml
  Backpack/src/main/res/values/dimens.xml
  app/screenshots/oss/debug/default/net.skyscanner.backpack.dialog.BpkDialogTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.dialog.BpkDialogTest_deprecated.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.dialog.BpkDialogTest_destructive.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.dialog.BpkDialogTest_flare.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.dialog.BpkDialogTest_fullscreen.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.dialog.BpkDialogTest_warning.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.dialog.BpkDialogTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.dialog.BpkDialogTest_deprecated.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.dialog.BpkDialogTest_destructive.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.dialog.BpkDialogTest_flare.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.dialog.BpkDialogTest_warning.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.dialog.BpkDialogTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.dialog.BpkDialogTest_deprecated.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.dialog.BpkDialogTest_destructive.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.dialog.BpkDialogTest_flare.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.dialog.BpkDialogTest_warning.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.dialog.BpkDialogTest_default.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.dialog.BpkDialogTest_deprecated.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.dialog.BpkDialogTest_destructive.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.dialog.BpkDialogTest_flare.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.dialog.BpkDialogTest_warning.png
  docs/view/Dialog/screenshots/destructive.png
  docs/view/Dialog/screenshots/destructive_dm.png
  docs/view/Dialog/screenshots/flare.png
  docs/view/Dialog/screenshots/flare_dm.png
  docs/view/Dialog/screenshots/success-three-buttons.png
  docs/view/Dialog/screenshots/success-three-buttons_dm.png
Labels: patch
