Repository Skyscanner/backpack-android, pull requests merged in 2023-10, with the labels that each got.

#1745 lumen/LMN-420 update Range slider to support custom thumb with label
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.slider.BpkSliderTest_rangeWithLabel.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.slider.BpkSliderTest_rangeWithLabel.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/slider/BpkSliderTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/SliderStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/slider/BpkSlider.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/slider/internal/BpkRangeSliderImpl.kt
  docs/compose/Slider/README.md
  docs/compose/Slider/screenshots/default.png
  docs/compose/Slider/screenshots/default_dm.png
Labels: minor

#1741 OGM-1973 Add selectableMonthRange parameter to Calendar2
  app/src/androidTest/java/net/skyscanner/backpack/calendar2/BpkCalendarTestCases.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/CalendarStoryType.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarCellsLayoutTests.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarRangeSelectionTests.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarCells.kt
Labels: minor

#1746 Set TopNavBar zIndex to 1
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt
Labels: patch

#1747 Add avd-name in attempt to reduce emulator boot failures
  .github/workflows/_build.yml
Labels: skip-changelog

#1756 LMN-525 Implement App search modal
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content_inputText.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_error.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_loading.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content_inputText.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_error.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_loading.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content_inputText.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_error.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_loading.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/appsearchmodal/BpkAppSearchModalTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/components/AppSearchModalComponent.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/AppSearchModalStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/BpkAppSearchModal.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkAppSearchModalImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSearchModalContent.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSearchModalError.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSearchModalLoading.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSection.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkShortcuts.kt
  docs/compose/AppSearchModal/README.md
  docs/compose/AppSearchModal/screenshots/content.png
  docs/compose/AppSearchModal/screenshots/content_dm.png
  docs/compose/AppSearchModal/screenshots/error.png
  docs/compose/AppSearchModal/screenshots/error_dm.png
  docs/compose/AppSearchModal/screenshots/loading.png
  docs/compose/AppSearchModal/screenshots/loading_dm.png
Labels: minor

#1758 Fix accessibility for text field
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/textfield/internal/BpkTextFieldImpl.kt
Labels: patch

#1759 Added support for leading icon on BpkBadge
  Backpack/src/main/java/net/skyscanner/backpack/badge/BpkBadge.kt
  Backpack/src/main/res/values/attrs.xml
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_destructiveWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_inverseWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_normalWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_outlineWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_strongWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_successWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_warningWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_destructiveWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_inverseWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_normalWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_outlineWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_strongWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_successWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_warningWithIcon.png
  app/src/androidTest/java/net/skyscanner/backpack/badge/BpkBadgeTest.kt
  app/src/main/res/layout/fragment_badge.xml
  docs/view/Badge/README.md
  docs/view/Badge/screenshots/default.png
  docs/view/Badge/screenshots/default_dm.png
Labels: minor

#1760 Fix BpkAppSearchModal animation
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/BpkAppSearchModal.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSearchModalLoading.kt
Labels: minor

#1772 LMN-678 BpkAppSearchModal subtitle annotatedString
  app/src/main/java/net/skyscanner/backpack/demo/compose/AppSearchModalStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/BpkAppSearchModal.kt
Labels: minor
