Repository Skyscanner/backpack-android, pull requests merged in 2023-12, with the labels that each got.

#1820 Switch githooks to standard git hook path
  build.gradle
Labels: skip-changelog

#1821 Lmn 849 fix subtitle text style of bpk rating
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.rating.BpkRatingTest_customContent.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.rating.BpkRatingTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.rating.BpkRatingTest_noScale.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.rating.BpkRatingTest_noTitle.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.rating.BpkRatingTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.rating.BpkRatingTest_default.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/rating/internal/BpkRatingComponents.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/rating/internal/BpkRatingLayout.kt
  docs/compose/Rating/screenshots/default.png
  docs/compose/Rating/screenshots/default_dm.png
Labels: patch

#1801 LMN-773: Add clear action for app search modal
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content_inputText.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_loading.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textfield.BpkTextFieldTest_withClearStatus.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content_inputText.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_loading.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content_inputText.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_loading.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.textfield.BpkTextFieldTest_withClearStatus.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/textfield/BpkTextFieldTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/AppSearchModalStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/TextFieldStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/ComponentListScreen.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/BpkAppSearchModal.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkAppSearchModalImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/fieldset/BpkFieldSet.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/textfield/BpkTextField.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/textfield/internal/BpkTextFieldImpl.kt
  docs/compose/AppSearchModal/README.md
  docs/compose/AppSearchModal/screenshots/loading.png
  docs/compose/AppSearchModal/screenshots/loading_dm.png
  docs/compose/TextField/README.md
  docs/compose/TextField/screenshots/clear.png
  docs/compose/TextField/screenshots/clear_dm.png
Labels: minor

#1830 Improve text field trailing icon behaviour
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.fieldset.BpkFieldSetTest_error.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.fieldset.BpkFieldSetTest_validated.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_error.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_validated.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textfield.BpkTextFieldTest_error.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textfield.BpkTextFieldTest_validated.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.fieldset.BpkFieldSetTest_error.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.fieldset.BpkFieldSetTest_validated.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_error.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_validated.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.textfield.BpkTextFieldTest_error.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.textfield.BpkTextFieldTest_validated.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_error.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_validated.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.textfield.BpkTextFieldTest_error.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.textfield.BpkTextFieldTest_validated.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/TextFieldStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/FieldStatusSwitcher.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/textfield/internal/BpkTextFieldImpl.kt
  docs/compose/FieldSet/screenshots/default.png
  docs/compose/FieldSet/screenshots/default_dm.png
  docs/compose/FieldSet/screenshots/disabled.png
  docs/compose/FieldSet/screenshots/disabled_dm.png
  docs/compose/FieldSet/screenshots/error.png
  docs/compose/FieldSet/screenshots/error_dm.png
  docs/compose/FieldSet/screenshots/validated.png
  docs/compose/FieldSet/screenshots/validated_dm.png
  docs/compose/TextField/README.md
  docs/compose/TextField/screenshots/clear.png
  docs/compose/TextField/screenshots/clear_dm.png
  docs/compose/TextField/screenshots/default.png
  docs/compose/TextField/screenshots/default_dm.png
  docs/compose/TextField/screenshots/disabled.png
  docs/compose/TextField/screenshots/disabled_dm.png
  docs/compose/TextField/screenshots/error.png
  docs/compose/TextField/screenshots/error_dm.png
  docs/compose/TextField/screenshots/text-area-disabled.png
  docs/compose/TextField/screenshots/text-area-disabled_dm.png
  docs/compose/TextField/screenshots/text-area-error.png
  docs/compose/TextField/screenshots/text-area-error_dm.png
  docs/compose/TextField/screenshots/text-area-validated.png
  docs/compose/TextField/screenshots/text-area-validated_dm.png
  docs/compose/TextField/screenshots/text-area.png
  docs/compose/TextField/screenshots/text-area_dm.png
  docs/compose/TextField/screenshots/validated.png
  docs/compose/TextField/screenshots/validated_dm.png
Labels: patch
