Repository Skyscanner/backpack-android, pull requests merged in 2023-05, with the labels that each got.

#1545 SONIC-1568: Image and flare dialog corrections
  .github/workflows/_build.yml
  CONTRIBUTING.md
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_destructive.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_flare.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_flareVertical.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageEndAlignment.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageStartAlignment.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageVertical.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_noIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_successOneButton.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_successThreeButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_successTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dialog.BpkDialogTest_warning.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_destructive.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_flare.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_flareVertical.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageEndAlignment.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageStartAlignment.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageVertical.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_noIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_successOneButton.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_successThreeButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_successTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_warning.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageEndAlignment.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageStartAlignment.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.dialog.BpkDialogTest_successOneButton.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/dialog/BpkDialogTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/DialogStory.kt
  app/src/main/res/drawable-nodpi/sunset.jpg
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/dialog/BpkDialog.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/dialog/internal/BpkDialogImpl.kt
  docs/compose/Dialog/screenshots/destructive.png
  docs/compose/Dialog/screenshots/destructive_dm.png
  docs/compose/Dialog/screenshots/flare.png
  docs/compose/Dialog/screenshots/flare_dm.png
  docs/compose/Dialog/screenshots/image-end-alignment.png
  docs/compose/Dialog/screenshots/image-end-alignment_dm.png
  docs/compose/Dialog/screenshots/image-start-alignment.png
  docs/compose/Dialog/screenshots/image-start-alignment_dm.png
  docs/compose/Dialog/screenshots/success-three-buttons.png
  docs/compose/Dialog/screenshots/success-three-buttons_dm.png
  docs/compose/Dialog/screenshots/warning.png
  docs/compose/Dialog/screenshots/warning_dm.png
Labels: patch

#1578 Migrated the Checkbox and RadioButton to MD3
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/checkbox/BpkCheckbox.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/radiobutton/BpkRadioButton.kt
Labels: patch

#1579 Fixed the BpkFloatingNotification content alignment
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withCta.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/internal/BpkFloatingNotification.kt
Labels: patch

#1581 Implemented the fix for Calendar2 weekdays style for some Chinese languages
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
Labels: patch

#1587 Switched Card to MD3
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.card.BpkCardTest_focused.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.card.BpkCardTest_largeCorner.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.card.BpkCardTest_noElevation.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.card.BpkCardTest_noPadding.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.card.BpkCardTest_smallCorner.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.card.BpkCardTest_unfocused.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthGreaterThanMinimum.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthSmallerThanMinimum.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.card.BpkCardTest_focused.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.card.BpkCardTest_noElevation.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.card.BpkCardTest_smallCorner.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.card.BpkCardTest_unfocused.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthGreaterThanMinimum.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthSmallerThanMinimum.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.card.BpkCardTest_smallCorner.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthGreaterThanMinimum.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthSmallerThanMinimum.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/CardStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/card/BpkCard.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/card/internal/BpkCardImpl.kt
Labels: major

#1588 Switched CardWrapper to MD3
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_emptyWrapper.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthGreaterThanMinimum.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthSmallerThanMinimum.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_emptyWrapper.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthGreaterThanMinimum.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthSmallerThanMinimum.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_emptyWrapper.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthGreaterThanMinimum.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthSmallerThanMinimum.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/cardwrapper/BpkCardWrapper.kt
  docs/compose/Card/screenshots/card-wrapper.png
  docs/compose/Card/screenshots/card-wrapper_dm.png
  docs/compose/Card/screenshots/default.png
  docs/compose/Card/screenshots/default_dm.png
Labels: patch

#1592 KOA-6015 Migrate horizontal nav to custom implementation – Compose
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.horizontalnav.BpkHorizontalNavTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.horizontalnav.BpkHorizontalNavTest_large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.horizontalnav.BpkHorizontalNavTest_largeWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.horizontalnav.BpkHorizontalNavTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.horizontalnav.BpkHorizontalNavTest_largeWithIcon.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.horizontalnav.BpkHorizontalNavTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.horizontalnav.BpkHorizontalNavTest_largeWithIcon.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/horizontalnav/BpkHorizontalNav.kt
Labels: patch

#1595 Updated to Node 18
  .nvmrc
  package-lock.json
  package.json
Labels: skip-changelog

#1602 KOA-6017 Update Switch design to MD3
  Backpack/src/main/java/net/skyscanner/backpack/toggle/BpkSwitch.kt
  Backpack/src/main/java/net/skyscanner/backpack/util/ColorStateList.kt
  Backpack/src/main/res/drawable/bpk_switch_decoration.xml
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.switch.BpkSwitchTest_customContent.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.switch.BpkSwitchTest_defaultChecked.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.switch.BpkSwitchTest_disabledChecked.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.switch.BpkSwitchTest_disabledUnchecked.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.toggle.BpkSwitchTest_defaultChecked.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.toggle.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.toggle.BpkSwitchTest_disabledChecked.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.toggle.BpkSwitchTest_disabledUnchecked.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.switch.BpkSwitchTest_defaultChecked.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.switch.BpkSwitchTest_disabledChecked.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.switch.BpkSwitchTest_disabledUnchecked.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.toggle.BpkSwitchTest_defaultChecked.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.toggle.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.toggle.BpkSwitchTest_disabledChecked.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.toggle.BpkSwitchTest_disabledUnchecked.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.toggle.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.toggle.BpkSwitchTest_defaultChecked.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.toggle.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.toggle.BpkSwitchTest_disabledChecked.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.toggle.BpkSwitchTest_disabledUnchecked.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/switch/BpkSwitch.kt
  docs/compose/Switch/screenshots/default.png
  docs/compose/Switch/screenshots/default_dm.png
  docs/view/Switch/screenshots/default.png
  docs/view/Switch/screenshots/default_dm.png
Labels: major

#1608 KOA-6112 Update Page Indicator demo
  app/src/main/java/net/skyscanner/backpack/demo/compose/PageIndicatorStory.kt
  docs/compose/PageIndicator/screenshots/default.png
  docs/compose/PageIndicator/screenshots/default_dm.png
Labels: skip-changelog
