Repository Skyscanner/backpack-android, pull requests merged in 2023-02, with the labels that each got.

#1426 Koa-4932 Create BpkStarRating as Compose
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.rating.BpkRatingTest_customContent.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.rating.BpkRatingTest_largeCustomContent.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.rating.BpkRatingTest_largeCustomContentMoSubtitle.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_aboveMaxRating.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_hotelStarRating4.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_negativeRating.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_ratingFullStar.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_ratingHalfStar.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_roundingTypeDown.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_roundingTypeUp.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_starSizeLarge.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_starSizeSmall.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_zeroRating.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_aboveMaxRating.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_hotelStarRating4.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_negativeRating.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_ratingFullStar.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_ratingHalfStar.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_roundingTypeDown.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_roundingTypeUp.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_starSizeLarge.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_starSizeSmall.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_zeroRating.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_aboveMaxRating.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_hotelStarRating4.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_negativeRating.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_ratingFullStar.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_ratingHalfStar.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_roundingTypeDown.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_roundingTypeUp.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_starSizeLarge.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_starSizeSmall.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_zeroRating.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/starrating/BpkStarRatingTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BpkStarRatingStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/RatingStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/starrating/BpkStarRating.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/ContentDescriptionScope.kt
  docs/compose/StarRating/README.md
  docs/compose/StarRating/screenshots/default.png
  docs/compose/StarRating/screenshots/default_dm.png
Labels: minor

#1454 KOA-5829 Switch git hook to Gradle
  .eslintignore
  .eslintrc
  .github/workflows/_build.yml
  .gitignore
  .husky/pre-commit
  .spelling
  CONTRIBUTING.md
  Dangerfile.df.kts
  babel.config.js
  build.gradle
  dangerfile.js
  hooks/pre-commit
  package-lock.json
  package.json
Labels: skip-changelog

#1457 Ensure danger only runs on PR and produces output
  .github/workflows/_build.yml
  templates/component/README.md
Labels: skip-changelog

#1450 SONIC-1204 BpkPageIndicator
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_lessThan5pagesDefault.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_lessThan5pagesOverImage.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_moreThan5pagesDefault.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_moreThan5pagesOverImage.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_lessThan5pagesDefault.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_lessThan5pagesOverImage.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_moreThan5pagesDefault.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_moreThan5pagesOverImage.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_lessThan5pagesDefault.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_lessThan5pagesOverImage.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_moreThan5pagesDefault.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.pageindicator.BpkPageIndicatorTest_moreThan5pagesOverImage.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/pageindicator/BpkPageIndicatorTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/PageIndicatorStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/pageindicator/BpkPageIndicator.kt
  docs/compose/PageIndicator/README.md
  docs/compose/PageIndicator/screenshots/default.png
  docs/compose/PageIndicator/screenshots/default_dm.png
Labels: minor

#1458 [KOA-5896]: Add new Origin icon
  app/screenshots/oss/debug/default/net.skyscanner.backpack.icon.BpkIconTest_large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.icon.BpkIconTest_small.png
  backpack-common/src/main/res/drawable-nodpi/bpk_origin.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_origin_sm.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkIcon.kt
  package-lock.json
  package.json
Labels: minor

#1460 Update pull request template
  .github/pull_request_template.md
Labels: skip-changelog

#1459 BD-6621: BPKCardWrapper Android(Compose)
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_emptyWrapper.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthGreaterThanMinimum.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthSmallerThanMinimum.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_emptyWrapper.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthGreaterThanMinimum.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthSmallerThanMinimum.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_emptyWrapper.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthGreaterThanMinimum.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardwrapper.BpkCardWrapperTest_wrapperWidthSmallerThanMinimum.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/cardwrapper/BpkCardWrapperTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/CardStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/CardWrapperStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/DividedCardStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/cardwrapper/BpkCardWrapper.kt
  docs/compose/Card/README.md
  docs/compose/Card/screenshots/card-wrapper.png
  docs/compose/Card/screenshots/card-wrapper_dm.png
  docs/compose/Card/screenshots/defalut_dm.png
  docs/compose/Card/screenshots/default.png
  docs/compose/Card/screenshots/default_dm.png
  docs/compose/Card/screenshots/divided-card.png
  docs/compose/Card/screenshots/divided-card_dm.png
Labels: minor

#1463 SONIC-1426 BpkFloatingNotification animation
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/FloatingNotificationStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/BpkFloatingNotification.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/internal/BpkFloatingNotification.kt
  docs/compose/Card/screenshots/default_dm.png
  docs/compose/FloatingNotification/README.md
  docs/compose/FloatingNotification/screenshots/default.png
  docs/compose/FloatingNotification/screenshots/default_dm.png
Labels: patch

#1464 SONIC-1418 Fix BpkTopNavBar background color in expanded mode
  Backpack/src/main/java/net/skyscanner/backpack/navbar/BpkNavBar.kt
  Backpack/src/main/java/net/skyscanner/backpack/navbar/internal/BpkCollapsingToolbarLayout.kt
  Backpack/src/main/res/drawable-night/navbar_content_scrim_background.xml
  Backpack/src/main/res/drawable/navbar_content_scrim_background.xml
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expanded.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_iconAndMenu.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_menu.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.navbar.BpkNavBarTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.navbar.BpkNavBarTest_expanded_iconAndMenu.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt
  docs/compose/NavBar/screenshots/collapsible_dm.png
  docs/view/NavBar/screenshots/expanded_dm.png
Labels: patch

#1466 BD-6667: Added attribute elevation to BpkDividedCard component
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.dividedcard.BpkDividedCardTest_noShadowCard.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dividedcard.BpkDividedCardTest_noShadowCard.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.dividedcard.BpkDividedCardTest_noShadowCard.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/dividedcard/BpkDividedCardTest.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/dividedcard/BpkDividedCard.kt
Labels: minor

#1467 KOA-5919 Rename lineThroughText to previousPrice on BpkPrice
  app/src/androidTest/java/net/skyscanner/backpack/compose/price/BpkPriceTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/PriceStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/BpkPrice.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceImpl.kt
  docs/compose/Price/README.md
Labels: patch

#1453 Koa-5883 Create BpkInteractiveStarRating in Compose
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_interactiveStarRating.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_interactiveStarRating.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.starrating.BpkStarRatingTest_interactiveStarRating.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/starrating/BpkStarRatingTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BpkInteractiveStarRatingStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BpkStarRatingStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/starrating/BpkStarRating.kt
  docs/compose/StarRating/README.md
  docs/compose/StarRatingInteractive/screenshots/default.png
  docs/compose/StarRatingInteractive/screenshots/default_dm.png
Labels: minor

#1471 Fix template sample
  templates/component/Story.kt
Labels: skip-changelog

#1465 Koa 5877 implement custom ksp processor for stories
  app/build.gradle
  app/src/androidTest/java/net/skyscanner/backpack/meta/StoriesTests.kt
  app/src/main/java/net/skyscanner/backpack/demo/MainActivity.kt
  app/src/main/java/net/skyscanner/backpack/demo/SettingsActivity.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ComponentUi.kt
  app/src/main/java/net/skyscanner/backpack/demo/meta/Component.kt
  app/src/main/java/net/skyscanner/backpack/demo/meta/ComposeStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/meta/Story.kt
  app/src/main/java/net/skyscanner/backpack/demo/meta/ViewStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/stories/SubStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/ComponentListScreen.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/ComponentScreen.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/SettingsThemeOption.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/StoryScreen.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/ViewInterop.kt
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/annotation/BpkPreviews.kt
  build.gradle
  meta-processor/build.gradle
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/Annotations.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/BackpackSymbolProcessor.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/Extensions.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/Models.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/References.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ComponentsVisitor.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ComposeStoriesVisitor.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ViewStoriesVisitor.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/writer/StoriesWriter.kt
  meta-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
  settings.gradle
Labels: minor

#1473 Ensure app is uninstalled before we attempt to install
  .github/workflows/_build.yml
Labels: skip-changelog

#1474 KOA-5924 Switch to new compose detekt fork
  .detekt-compose.yml
  build.gradle
Labels: skip-changelog

#1478 Koa 5892 Implement support of custom KSP processor for screenshots
  app/src/androidTest/java/net/skyscanner/backpack/docs/GenerateScreenshots1.kt
  app/src/androidTest/java/net/skyscanner/backpack/meta/StoriesTests.kt
  app/src/main/java/net/skyscanner/backpack/demo/meta/Component.kt
  app/src/main/java/net/skyscanner/backpack/demo/meta/StoriesRepository.kt
  app/src/main/java/net/skyscanner/backpack/demo/meta/ViewStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/ComponentListScreen.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/ComponentScreen.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/DemoScaffold.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/StoryScreen.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/Models.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/References.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/AbstractStoriesVisitor.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ComponentsVisitor.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ComposeStoriesVisitor.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ViewStoriesVisitor.kt
  meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/writer/StoriesWriter.kt
Labels: skip-changelog

#1468 Skyscanner/sonic 1203 bpk carousel
  app/build.gradle
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_multipleImageDarkMode.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_multipleImageDefault.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_setCurrentImage.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_singleImageDefault.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_multipleImageDarkMode.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_multipleImageDefault.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_setCurrentImage.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_singleImageDefault.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_multipleImageDefault.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_setCurrentImage.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.carousel.BpkCarouselTest_singleImageDefault.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/carousel/BpkCarouselTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/CarouselStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/drawable-nodpi/beach.jpg
  app/src/main/res/drawable-nodpi/city.jpg
  app/src/main/res/values/strings.xml
  backpack-compose/build.gradle
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/carousel/BpkCarousel.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/carousel/BpkCarouselState.kt
  build.gradle
  docs/compose/Carousel/README.md
  docs/compose/Carousel/screenshots/default.png
  docs/compose/Carousel/screenshots/default_dm.png
Labels: minor
