Repository Skyscanner/backpack-android, pull requests merged in 2023-07, with the labels that each got.

#1647 KOA-6021 Update NavBarfor MD3 – Compose
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_collapsedTransparentNavBar.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expanded.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedNoActions.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedNoActionsTransparentNavBar.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedNoNavIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedNoNavIconTransparentNavBar.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedTransparentNavBar.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_windowInsets.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_windowInsetsTransparentNavBar.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expanded.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedTransparentNavBar.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expanded.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedNoActions.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedNoActionsTransparentNavBar.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedNoNavIcon.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedNoNavIconTransparentNavBar.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedTransparentNavBar.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/NavBarStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/BpkTopNavBar.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/TopNavBarState.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/TopAppBarLayout.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/TopNavBarSizes.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/TopNavBarState.kt
Labels: patch

#1651 KOA-6022 Update NavBar for MD3 – View
  Backpack/src/main/java/net/skyscanner/backpack/navbar/BpkNavBar.kt
  Backpack/src/main/java/net/skyscanner/backpack/navbar/internal/BpkCollapsingToolbarLayout.kt
  Backpack/src/main/java/net/skyscanner/backpack/navbar/internal/BpkToolbar.kt
  Backpack/src/main/res/values/attrs.xml
  Backpack/src/main/res/values/dimens.xml
  app/screenshots/oss/debug/default/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_icon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_iconAndMenu.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_menu.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.navbar.BpkNavBarTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.navbar.BpkNavBarTest_expanded_icon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.navbar.BpkNavBarTest_expanded_iconAndMenu.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.navbar.BpkNavBarTest_expanded_menu.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_iconAndMenu.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_menu.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.navbar.BpkNavBarTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.navbar.BpkNavBarTest_expanded_iconAndMenu.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_iconAndMenu.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_menu.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.navbar.BpkNavBarTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.navbar.BpkNavBarTest_expanded_iconAndMenu.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_iconAndMenu.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.navbar.BpkNavBarTest_collapsed_menu.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.navbar.BpkNavBarTest_default.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.navbar.BpkNavBarTest_expanded_iconAndMenu.png
  app/src/main/res/layout/fragment_nav_bar.xml
  app/src/main/res/layout/fragment_nav_bar_with_icon.xml
  app/src/main/res/layout/fragment_nav_bar_with_menu.xml
  app/src/main/res/values/themes.xml
  docs/view/NavBar/README.md
Labels: major

#1655 Removed MD2 completely
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlist.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.text.BpkTextTest_hero1.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlist.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlist.png
  backpack-compose/build.gradle
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/CompositionProviders.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkBottomSheet.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/internal/BpkButtonImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarHeader.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/fab/BpkFab.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/internal/BpkFloatingNotification.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/theme/BpkTheme.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/CompositionProviders.kt
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
  backpack-lint/src/test/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetectorTest.kt
  gradle/libs.versions.toml
Labels: skip-changelog

#1654 Fixed the flaky tests for BpkSelect component
  app/src/androidTest/java/net/skyscanner/backpack/compose/BpkSnapshotTest.kt
Labels: skip-changelog

#1662 KOA-6215 Added icon for AI
  app/screenshots/oss/debug/default/net.skyscanner.backpack.icon.BpkIconTest_large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.icon.BpkIconTest_small.png
  backpack-common/src/main/res/drawable-nodpi/bpk_ai.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_ai_sm.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkIcon.kt
  package-lock.json
  package.json
Labels: minor

#1660 KOA-6208 Migrate the screenshot server to KTor
  app/build.gradle
  app/src/androidTest/java/net/skyscanner/backpack/docs/RemoteScreenGrab.kt
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/net/skyscanner/backpack/screenshots/ScreenshotTestsServer.kt
  gradle/libs.versions.toml
Labels: skip-changelog

#1663 Koa-6211 Align card wrapper screenshots for Android
  app/src/main/java/net/skyscanner/backpack/demo/compose/CardWrapperStory.kt
  app/src/main/res/values/strings.xml
  docs/compose/Card/screenshots/card-wrapper.png
  docs/compose/Card/screenshots/card-wrapper_dm.png
Labels: skip-changelog

#1658 LMN-26 add progress bar component
  .idea/inspectionProfiles/ktlint.xml
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_noProgress.Large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_noProgress.Small.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressAboveMaximum.Large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressAboveMaximum.Small.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressBelowMaximum.Large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressBelowMaximum.Small.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedNoProgress.Large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedNoProgress.Small.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAboveMaximum.Large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAboveMaximum.Small.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAtStep.Large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAtStep.Small.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressInBetweenSteps.Large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressInBetweenSteps.Small.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_noProgress.Large.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_noProgress.Small.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressAboveMaximum.Large.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressAboveMaximum.Small.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressBelowMaximum.Large.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressBelowMaximum.Small.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedNoProgress.Large.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedNoProgress.Small.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAboveMaximum.Large.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAboveMaximum.Small.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAtStep.Large.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAtStep.Small.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressInBetweenSteps.Large.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressInBetweenSteps.Small.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_noProgress.Large.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_noProgress.Small.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressAboveMaximum.Large.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressAboveMaximum.Small.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressBelowMaximum.Large.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_progressBelowMaximum.Small.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedNoProgress.Large.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedNoProgress.Small.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAboveMaximum.Large.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAboveMaximum.Small.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAtStep.Large.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressAtStep.Small.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressInBetweenSteps.Large.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.progressbar.BpkProgressBarTest_steppedProgressInBetweenSteps.Small.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/progressbar/BpkProgressBarTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/components/ProgressBarComponent.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ProgressBarStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/progressbar/BpkProgressBar.kt
  docs/compose/ProgressBar/README.md
  docs/compose/ProgressBar/screenshots/default.png
  docs/compose/ProgressBar/screenshots/default_dm.png
Labels: minor

#1650 KOA-6043 Compose map markers
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.map.BpkIconMapMarkerTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.map.BpkIconMapMarkerTest_disabled.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.map.BpkIconMapMarkerTest_focused.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.map.BpkPointerMapMarkerTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_disabled.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_focused.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_viewed.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.map.BpkIconMapMarkerTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.map.BpkIconMapMarkerTest_disabled.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.map.BpkIconMapMarkerTest_focused.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.map.BpkPointerMapMarkerTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_disabled.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_focused.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_viewed.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.map.BpkIconMapMarkerTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.map.BpkIconMapMarkerTest_disabled.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.map.BpkIconMapMarkerTest_focused.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.map.BpkPointerMapMarkerTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_disabled.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_focused.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.map.BpkPriceMapMarkerTest_viewed.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/map/BpkIconMapMarkerTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/map/BpkPointerMapMarkerTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/map/BpkPriceMapMarkerTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/MapStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/build.gradle
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkIconMapMarker.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPointerMapMarker.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPriceMapMarker.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/internal/IconMarkerShape.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/ComposeToBitmap.kt
  docs/compose/Maps/README.md
  docs/compose/Maps/screenshots/icon.png
  docs/compose/Maps/screenshots/icon_dm.png
  docs/compose/Maps/screenshots/pointer.png
  docs/compose/Maps/screenshots/pointer_dm.png
  docs/compose/Maps/screenshots/price.png
  docs/compose/Maps/screenshots/price_dm.png
  gradle/libs.versions.toml
Labels: minor
