Repository Skyscanner/backpack-android, pull requests merged in 2023-01, with the labels that each got.

#1387 Fix snapshot flakiness
  app/src/androidTest/java/net/skyscanner/backpack/BpkSnapshotTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/bottomsheet/BpkBottomSheetTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/snackbar/BpkSnackbarTests.kt
Labels: skip-changelog

#1393 Fix Readme screenshots
  docs/compose/BarChart/README.md
  docs/compose/Slider/README.md
Labels: skip-changelog

#1397 KOA-5838 Rename border radius pill to xl
  .nvmrc
  Backpack/src/main/java/net/skyscanner/backpack/chip/internal/Utils.kt
  Backpack/src/main/res/drawable/bpk_bg_rating_badge.xml
  Backpack/src/main/res/drawable/chip_outline_background.xml
  Backpack/src/main/res/values/backpack.radii.xml
  CHANGELOG.md
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkBorderRadius.kt
  package-lock.json
  package.json
Labels: major

#1398 KOA-5642 Cleanup automirror logic
  app/src/main/java/net/skyscanner/backpack/demo/compose/IconsStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkIcon.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkIcons.kt
Labels: skip-changelog

#1407 Made Depart and Return icons auto-mirrored
  backpack-common/src/main/res/drawable-nodpi/bpk_depart.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_depart_sm.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_return.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_return_sm.xml
  package-lock.json
  package.json
Labels: patch

#1402 SONIC-1230 Make BpkFloatingNotification width wider
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withCta.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withCta.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withCta.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIcon.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/internal/BpkFloatingNotification.kt
  docs/compose/FloatingNotification/screenshots/default.png
  docs/compose/FloatingNotification/screenshots/default_dm.png
Labels: patch

#1411 SONIC-1230 BpkFloatingNotification width correction
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withCta.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withCta.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withCta.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIcon.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/BpkFloatingNotification.kt
  docs/compose/FloatingNotification/screenshots/default.png
  docs/compose/FloatingNotification/screenshots/default_dm.png
Labels: patch

#1412 Fixed copy task
  app/screenshots.gradle
Labels: skip-changelog

#1414 Fix flaky bottomsheet test
  Backpack/src/main/java/net/skyscanner/backpack/bottomsheet/BpkBottomSheetBehaviour.kt
  app/screenshots/oss/debug/default/net.skyscanner.backpack.bottomsheet.BpkBottomSheetTest_default.png
  app/src/androidTest/java/net/skyscanner/backpack/bottomsheet/BpkBottomSheetTest.kt
Labels: skip-changelog

#1415 Always record the snapshots on the CI
  .github/workflows/_build.yml
  CONTRIBUTING.md
  scripts/verify_screenshot_tests.sh
Labels: skip-changelog

#1420 KOA-5828 Remove static colours in compose
  app/src/androidTest/java/net/skyscanner/backpack/compose/spinner/BpkSpinnerTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ChipStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ColorsStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/SpinnerStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/Tokens.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/badge/BpkBadge.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColor.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColors.kt
  backpack-compose/tokens.gradle.kts
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkColors.kt
Labels: major

#1422 KOA-5828 Migrate colour token generation to compose
  .detekt.yml
  Backpack/src/main/res/values-night/backpack.internal.color.xml
  Backpack/src/main/res/values-night/backpack.semantic.color.xml
  Backpack/src/main/res/values/backpack.color.xml
  Backpack/src/main/res/values/backpack.internal.color.xml
  Backpack/src/main/res/values/backpack.semantic.color.xml
  Backpack/tokens.gradle.kts
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkBorderRadius.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkBorderSize.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColors.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkElevation.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkFontSize.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkIcon.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkLetterSpacing.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkLineHeight.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkSpacing.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkTypography.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/internal/BpkButtonColors.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/internal/BpkChipColors.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/internal/BpkSkeletonColors.kt
  backpack-lint/build.gradle
  backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkDeprecatedTokens.kt
  backpack-lint/tokens.gradle.kts
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkColors.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkDeprecatedTokens.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkOutput.kt
  gulpfile.js
  package-lock.json
  package.json
  templates/BackpackColor.njk
  templates/BackpackDeprecation.njk
Labels: skip-changelog

#1425 Fixed the screenshots issue
  buildSrc/src/main/kotlin/net/skyscanner/backpack/screenshots/ScreenshotTestsServer.kt
Labels: skip-changelog

#1431 Bump Kotlin & Compose
  build.gradle
  buildSrc/build.gradle.kts
Labels: dependencies, java

#1434 Cleanup JS token generation
  .github/workflows/_build.yml
  CONTRIBUTING.md
  gulpfile.js
  package-lock.json
  package.json
Labels: skip-changelog

#1436 SONIC-1362 Fix BpkTopNavBar scrollable elevation
  app/src/main/java/net/skyscanner/backpack/demo/compose/CollapsibleNavigationBarStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt
  docs/compose/NavBar/screenshots/collapsible.png
  docs/compose/NavBar/screenshots/collapsible_dm.png
Labels: patch
