Repository Skyscanner/backpack-android, pull requests merged in 2023-08, with the labels that each got.

#1664 [NEUT-1547] - Bkp Section Header
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithButton.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescription.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescriptionAndButton.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDark.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithButton.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescription.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescriptionAndButton.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.text.BpkTextTest_hero1.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.text.BpkTextTest_hero2.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithButton.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescription.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescriptionAndButton.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDark.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithButton.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescription.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescriptionAndButton.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithButton.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescription.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescriptionAndButton.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDark.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithButton.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescription.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescriptionAndButton.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/sectionheader/BpkSectionHeaderTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/components/SectionHeaderComponent.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/SectionHeaderStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/sectionheader/BpkSectionHeader.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/sectionheader/internal/BpkSectionHeaderImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/DeviceUtil.kt
  docs/compose/SectionHeader/README.md
  docs/compose/SectionHeader/screenshots/default.png
  docs/compose/SectionHeader/screenshots/default_dm.png
  docs/compose/SectionHeader/screenshots/ondark.png
  docs/compose/SectionHeader/screenshots/ondark_dm.png
Labels: minor

#1677 Add bpkbutton content description
  app/src/main/java/net/skyscanner/backpack/demo/compose/ButtonsStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/button/internal/BpkButtonImplTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/BpkButton.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/internal/BpkButtonImpl.kt
Labels: minor

#1679 Remove silent publishing option
  .github/workflows/release.yml
Labels: skip-changelog

#1691 Koa-6243 Change calendar in range colour for android
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/view/CalendarDaySelectionBackground.kt
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withDisabledDates_SelectRange.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withRangeSet.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withWholeMonthSet.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withRangeSet.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
  docs/compose/Calendar2/screenshots/day-labels.png
  docs/compose/Calendar2/screenshots/day-labels_dm.png
  docs/compose/Calendar2/screenshots/pre-selected-range.png
  docs/compose/Calendar2/screenshots/pre-selected-range_dm.png
  docs/compose/Calendar2/screenshots/selection-whole-month.png
  docs/compose/Calendar2/screenshots/selection-whole-month_dm.png
  docs/view/Calendar2/screenshots/day-labels.png
  docs/view/Calendar2/screenshots/day-labels_dm.png
  docs/view/Calendar2/screenshots/pre-selected-range.png
  docs/view/Calendar2/screenshots/pre-selected-range_dm.png
  docs/view/Calendar2/screenshots/selection-whole-month.png
  docs/view/Calendar2/screenshots/selection-whole-month_dm.png
Labels: patch

#1692 OGM-1915 Add extra small BpkPriceSize to BpkPriceImpl
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.ExtraSmall_End.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.ExtraSmall_Start.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.ExtraSmall_End.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.ExtraSmall_Start.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.ExtraSmall_End.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.ExtraSmall_Start.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.ExtraSmall_End.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.ExtraSmall_Start.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.ExtraSmall_End.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.ExtraSmall_Start.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.ExtraSmall_End.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.ExtraSmall_Start.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.ExtraSmall_End.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.ExtraSmall_Start.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.ExtraSmall_End.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.ExtraSmall_Start.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.ExtraSmall_End.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.ExtraSmall_Start.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.ExtraSmall_End.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.ExtraSmall_Start.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.ExtraSmall_End.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.ExtraSmall_Start.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.ExtraSmall_End.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.ExtraSmall_Start.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/PriceStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/BpkPrice.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceImpl.kt
  docs/compose/Price/README.md
  docs/compose/Price/screenshots/extra-small.png
  docs/compose/Price/screenshots/extra-small_dm.png
  docs/compose/Price/screenshots/large.png
  docs/compose/Price/screenshots/large_dm.png
  docs/compose/Price/screenshots/small.png
  docs/compose/Price/screenshots/small_dm.png
Labels: minor

#1693 Updated BpkBottomSheet.kt & BpkModalBottomSheet to support custom BpkDragHandleStyle
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_imageModelDark.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_onImageLight.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_imageModelDark.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_onImageLight.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/bottomsheet/BpkBottomSheetTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/BottomSheetStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkBottomSheet.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkModalBottomSheet.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/internal/BottomSheetContent.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/internal/BpkBottomSheetHandle.kt
  docs/compose/BottomSheet/README.md
  docs/compose/BottomSheet/screenshots/default.png
  docs/compose/BottomSheet/screenshots/default_dm.png
  docs/compose/BottomSheet/screenshots/image-content-sheet-with-light-draghandle.png
  docs/compose/BottomSheet/screenshots/image-content-sheet-with-light-draghandle_dm.png
  docs/compose/BottomSheet/screenshots/modal-sheet-with-dark-draghandle.png
  docs/compose/BottomSheet/screenshots/modal-sheet-with-dark-draghandle_dm.png
  docs/compose/BottomSheet/screenshots/modal.png
  docs/compose/BottomSheet/screenshots/modal_dm.png
Labels: minor

#1700 Add BpkTextArea widget for compose
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_disabled.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_disabledPlaceholder.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_error.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_multiline.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_multilinePlaceholder.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_placeholder.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_readOnly.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_validated.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_disabled.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_disabledPlaceholder.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_error.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_placeholder.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_validated.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_error.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_multilinePlaceholder.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.textarea.BpkTextAreaTest_validated.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/textarea/BpkTextAreaTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/TextFieldStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/textarea/BpkTextArea.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/textfield/internal/BpkTextFieldImpl.kt
  docs/compose/FieldSet/screenshots/default.png
  docs/compose/FieldSet/screenshots/default_dm.png
  docs/compose/FieldSet/screenshots/disabled.png
  docs/compose/FieldSet/screenshots/disabled_dm.png
  docs/compose/FieldSet/screenshots/error.png
  docs/compose/FieldSet/screenshots/error_dm.png
  docs/compose/FieldSet/screenshots/validated.png
  docs/compose/FieldSet/screenshots/validated_dm.png
  docs/compose/TextField/README.md
  docs/compose/TextField/screenshots/default.png
  docs/compose/TextField/screenshots/default_dm.png
  docs/compose/TextField/screenshots/disabled.png
  docs/compose/TextField/screenshots/disabled_dm.png
  docs/compose/TextField/screenshots/error.png
  docs/compose/TextField/screenshots/error_dm.png
  docs/compose/TextField/screenshots/text-area-disabled.png
  docs/compose/TextField/screenshots/text-area-disabled_dm.png
  docs/compose/TextField/screenshots/text-area-error.png
  docs/compose/TextField/screenshots/text-area-error_dm.png
  docs/compose/TextField/screenshots/text-area-validated.png
  docs/compose/TextField/screenshots/text-area-validated_dm.png
  docs/compose/TextField/screenshots/text-area.png
  docs/compose/TextField/screenshots/text-area_dm.png
  docs/compose/TextField/screenshots/validated.png
  docs/compose/TextField/screenshots/validated_dm.png
Labels: minor

#1702 KOA-6243 Fixed calendar range colour between months
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarSpaceCell.kt
Labels: patch

#1707 Fixed AppCenter upload
  .github/workflows/release.yml
Labels: skip-changelog
