Repository Skyscanner/backpack-android, pull requests merged in 2023-03, with the labels that each got.

#1485 Adding FlightLeg compose component
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegTest.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_simpleLegTest.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.text.BpkTextTest_hero2.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegTest.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_simpleLegTest.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegTest.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_simpleLegTest.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/flightleg/BpkFlightLegTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/FlightLegStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/flightleg/BpkFlightLeg.kt
  docs/compose/FlightLeg/README.md
  docs/compose/FlightLeg/screenshots/default.png
  docs/compose/FlightLeg/screenshots/default_dm.png
Labels: minor

#1490 KOA-5923 Ensure detekt runs as expected on all files
  .detekt.yml
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/model/CalendarRangeTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarControllerTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/presenter/HighlightedDaysAdapterTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/view/NonDrawnDaysOffset.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/view/WeekdayViewHeaderTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/BpkCalendarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/BpkTestRunner.kt
  app/src/androidTest/java/net/skyscanner/backpack/VariantFilter.kt
  app/src/androidTest/java/net/skyscanner/backpack/barchart/BpkBarchartTests.kt
  app/src/androidTest/java/net/skyscanner/backpack/bottomnav/BpkBottomNavTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/button/BpkButtonTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/calendar/BpkCalendarTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/calendar2/BpkCalendarTestCases.kt
  app/src/androidTest/java/net/skyscanner/backpack/card/BpkCardTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/checkbox/BpkCheckboxTests.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/BpkSnapshotTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/button/BpkButtonTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/cardbutton/BpkCardButtonTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/cardwrapper/BpkCardWrapperTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/carousel/BpkCarouselTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/dialog/BpkDialogTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/dividedcard/BpkDividedCardTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/floatingnotification/BpkFloatingNotificationTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/pageindicator/BpkPageIndicatorTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/price/BpkPriceTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/skeleton/BpkSkeletonTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/compose/text/BpkTextTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/dialog/BpkDialogTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/GenerateScreenshots.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/GenerateScreenshots1.kt
  app/src/androidTest/java/net/skyscanner/backpack/docs/RemoteScreenGrab.kt
  app/src/androidTest/java/net/skyscanner/backpack/flare/BpkFlareTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/meta/StoriesTests.kt
  app/src/androidTest/java/net/skyscanner/backpack/nudger/BpkNudgerTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/overlay/BpkOverlayTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/skeleton/BpkHeadlineSkeletonTest.kt
  app/src/androidTest/java/net/skyscanner/backpack/text/BpkTextFieldTests.kt
  app/src/androidTest/java/net/skyscanner/backpack/toggle/BpkSwitchTest.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarCellsLayoutTests.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarInfoTests.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarRangeSelectionTests.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarSettersTests.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/util/TestStateMachine.kt
  backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt
  build.gradle
  buildSrc/src/main/kotlin/net/skyscanner/backpack/screenshots/ScreenshotTestsServer.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkColors.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkDeprecatedTokens.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkDimensions.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkDurations.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkFormat.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkIcons.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkOutput.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkTextStyles.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkTextUnits.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/Pipeline.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/Source.kt
Labels: skip-changelog

#1492 Aligned the navIcon argument for NavBar for Compose
  app/src/androidTest/java/net/skyscanner/backpack/compose/navigationbar/BpkTopNavBarTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/NavBarStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/BpkTopNavBar.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt
Labels: major

#1505 Removed MD mappings from BpkTheme
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_textOnly.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.floatingnotification.BpkFloatingNotificationTest_withIconAndCta.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/internal/BpkFloatingNotification.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/theme/BpkTheme.kt
Labels: skip-changelog

#1515 KOA-5631 Remove usage of activity test rule for docs generation
  app/screenshots.gradle
  app/src/androidTest/java/net/skyscanner/backpack/docs/GenerateScreenshots.kt
  app/src/debug/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/net/skyscanner/backpack/demo/stories/ToastStory.kt
  app/src/screenshots/java/net/skyscanner/backpack/demo/BackpackDemoTheme.kt
  app/src/screenshots/res/values/backpack.animation.xml
  app/src/screenshots/res/values/themes.xml
  buildSrc/src/main/kotlin/net/skyscanner/backpack/screenshots/ScreenshotTestsServer.kt
Labels: skip-changelog

#1516 Removed BpkBaseActivity.kt
  CONTRIBUTING.md
  app/src/main/java/net/skyscanner/backpack/demo/BpkBaseActivity.kt
  app/src/main/java/net/skyscanner/backpack/demo/MainActivity.kt
  app/src/main/java/net/skyscanner/backpack/demo/ShakeListener.kt
  app/src/main/java/net/skyscanner/backpack/demo/stories/MapStory.kt
Labels: skip-changelog

#1517 Add supernova as a dependency
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: dependencies

#1520 [KOA-5992] Bump bpk-svgs to update baggage icons
  app/screenshots/oss/debug/default/net.skyscanner.backpack.icon.BpkIconTest_large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.icon.BpkIconTest_small.png
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_cabin.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_cabin_add.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_cabin_add_sm.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_cabin_not_included.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_cabin_not_included_sm.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_cabin_sm.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_checked.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_checked_add.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_checked_add_sm.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_checked_not_included.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_checked_not_included_sm.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_checked_sm.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_generic.xml
  backpack-common/src/main/res/drawable-nodpi/bpk_baggage_generic_sm.xml
  package-lock.json
  package.json
Labels: minor

#1521 [NO JIRA]: Fix supernova doc deployment step
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: skip-changelog

#1531 KOA 5988 Migrate to gradle central dependency declaration
  .github/dependabot.yml
  Backpack/build.gradle
  android-configuration.gradle
  app/build.gradle
  app/src/main/java/net/skyscanner/backpack/demo/BackpackDemoApplication.kt
  app/src/main/java/net/skyscanner/backpack/demo/meta/Component.kt
  app/src/main/java/net/skyscanner/backpack/demo/meta/ComposeStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/meta/ViewStory.kt
  backpack-common/build.gradle
  backpack-compose/build.gradle
  backpack-lint/build.gradle
  build.gradle
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  dokka.gradle
  gradle/libs.versions.toml
  meta-processor/build.gradle
Labels: skip-changelog

#1529 SONIC-1554 BpkFlightLeg carrier logo correction
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegLongStopsTest.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegShortStopsTest.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegTest.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_simpleLegTest.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegLongStopsTest.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegShortStopsTest.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegTest.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_simpleLegTest.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegLongStopsTest.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegShortStopsTest.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_completeLegTest.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_simpleLegTest.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/flightleg/BpkFlightLegTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/FlightLegStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/flightleg/BpkFlightLeg.kt
  docs/compose/FlightLeg/screenshots/default.png
  docs/compose/FlightLeg/screenshots/default_dm.png
Labels: minor

#1530 Koa-5408 Added a search bar in the demo app
  app/src/main/java/net/skyscanner/backpack/demo/ui/ComponentListScreen.kt
Labels: minor
