Repository Skyscanner/backpack-android, pull requests merged in 2024-07, with the labels that each got.

#2030 RALP-4865 Use ubuntu-22.04 instead of ubuntu-latest
  .github/workflows/_build.yml
  .github/workflows/label-check.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: skip-changelog

#2033 Enable custom content description for the bottom sheet title
  app/src/main/java/net/skyscanner/backpack/demo/compose/BottomSheetStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkModalBottomSheetTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkModalBottomSheet.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/internal/BpkModalBottomSheetImpl.kt
  docs/compose/BottomSheet/README.md
Labels: minor

#2041 NoJira - BpkAppSearchModal execute hide animation when place selected
  app/src/main/java/net/skyscanner/backpack/demo/compose/AppSearchModalStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/BpkAppSearchModal.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkAppSearchModalImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSearchModalContent.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSection.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkShortcuts.kt
Labels: minor

#2038 Ogm 2609 android add icon as label support to calendar cell info
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/list/CalendarCellDayHolder.kt
  Backpack/src/main/res/layout/view_bpk_calendar_day.xml
  app/screenshots/oss/debug/default/net.skyscanner.backpack.calendar2.BpkCalendarTest_labeled.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_labeled.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.calendar2.BpkCalendarTest_labeled.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_labeled.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/CalendarStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/CalendarStoryType.kt
  app/src/main/java/net/skyscanner/backpack/demo/stories/Calendar2Story.kt
  app/src/test/java/net/skyscanner/backpack/calendar2/BpkCalendarTestCases.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarInfoTests.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/icon/BpkIcon.kt
  docs/compose/Calendar2/README.md
  docs/compose/Calendar2/screenshots/day-icon-as-labels.png
  docs/compose/Calendar2/screenshots/day-icon-as-labels_dm.png
  docs/view/Calendar2/screenshots/day-icon-as-labels.png
  docs/view/Calendar2/screenshots/day-icon-as-labels_dm.png
Labels: major

#2043 Update doc
  docs/compose/Calendar2/README.md
  docs/view/Calendar2/README.md
Labels: minor

#2047 Ogm calendar 2 cell info icon
  Backpack/src/main/java/net/skyscanner/backpack/calendar2/list/CalendarCellDayHolder.kt
Labels: minor

#2046 Revert - BpkAppSearchModal execute hide animation
  app/src/main/java/net/skyscanner/backpack/demo/compose/AppSearchModalStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/BpkAppSearchModal.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkAppSearchModalImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSearchModalContent.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSection.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkShortcuts.kt
Labels: minor
