Repository Skyscanner/backpack-android, pull requests merged in 2024-03, with the labels that each got.

#1897 Add navigation bar in bottom sheet modal
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_imageModelDarkWithTopBar.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_modal.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_modalWithTopBar.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_imageModelDarkWithTopBar.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_modal.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_modalWithTopBar.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_modal.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_modalWithTopBar.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/BottomSheetStory.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/net/skyscanner/backpack/compose/bottomsheet/BpkBottomSheetTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkModalBottomSheet.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/internal/BpkModalBottomSheetImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt
  docs/compose/BottomSheet/README.md
  docs/compose/BottomSheet/screenshots/image-modal-sheet-with-topbar-and-dark-drag-handle.png
  docs/compose/BottomSheet/screenshots/image-modal-sheet-with-topbar-and-dark-drag-handle_dm.png
  docs/compose/BottomSheet/screenshots/modal-with-topbar.png
  docs/compose/BottomSheet/screenshots/modal-with-topbar_dm.png
  docs/compose/BottomSheet/screenshots/modal.png
  docs/compose/BottomSheet/screenshots/modal_dm.png
Labels: minor

#1898 expose inlineContent
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/text/BpkText.kt
Labels: minor

#1900 Remove deprecated colours in compose
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColors.kt
  buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkColors.kt
Labels: patch

#1902 New component - Navigation Tab Group
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationtabgroup.BpkNavigationTabGroupTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationtabgroup.BpkNavigationTabGroupTest_onDark.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.navigationtabgroup.BpkNavigationTabGroupTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.navigationtabgroup.BpkNavigationTabGroupTest_onDark.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.navigationtabgroup.BpkNavigationTabGroupTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.navigationtabgroup.BpkNavigationTabGroupTest_onDark.png
  app/src/main/java/net/skyscanner/backpack/demo/components/NavigationTabGroupComponent.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/NavigationTabGroupStory.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/net/skyscanner/backpack/compose/navigationtabgroup/BpkNavigationTabGroupTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationtabgroup/BpkNavigationTabGroup.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationtabgroup/internal/BpkNavigationTab.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationtabgroup/internal/BpkNavigationTabGroupImpl.kt
  docs/compose/NavigationTabGroup/README.md
  docs/compose/NavigationTabGroup/screenshots/default.png
  docs/compose/NavigationTabGroup/screenshots/default_dm.png
  package-lock.json
  package.json
Labels: minor

#1903 Fix Chip background not clipped when pressed
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content_inputText.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_default.RailWithStickyChip.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_default.RailWithoutStickyChip.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_default.Wrap.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_dark.RailWithStickyChip.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_dark.RailWithoutStickyChip.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_dark.Wrap.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_image.RailWithStickyChip.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_image.RailWithoutStickyChip.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_image.Wrap.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_default.Rail.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_default.Wrap.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onDark.Rail.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onDark.Wrap.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onImage.Rail.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onImage.Wrap.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_chip_grid.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content_inputText.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_default.RailWithStickyChip.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_default.RailWithoutStickyChip.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_default.Wrap.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_dark.RailWithStickyChip.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_dark.RailWithoutStickyChip.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_dark.Wrap.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_image.RailWithStickyChip.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_image.RailWithoutStickyChip.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_image.Wrap.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_default.Rail.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_default.Wrap.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onDark.Rail.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onDark.Wrap.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onImage.Rail.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onImage.Wrap.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_chip_grid.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.appsearchmodal.BpkAppSearchModalTest_content_inputText.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_default.RailWithStickyChip.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_default.RailWithoutStickyChip.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_default.Wrap.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_dark.RailWithStickyChip.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_dark.RailWithoutStickyChip.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_dark.Wrap.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_image.RailWithStickyChip.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_image.RailWithoutStickyChip.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkMultiSelectChipGroupTest_on_image.Wrap.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_default.Rail.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_default.Wrap.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onDark.Rail.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onDark.Wrap.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onImage.Rail.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.chipgroup.BpkSingleSelectChipGroupTest_onImage.Wrap.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_chip_grid.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/chip/internal/BpkChipImpl.kt
Labels: minor

#1914 Improve danger checks
  .gitignore
  Dangerfile.df.kts
Labels: skip-changelog
