Repository Skyscanner/backpack-android, pull requests merged in 2024-02, with the labels that each got.

#1871 [NOJIRA] Fix Default badge type to be Normal in View
  Backpack/src/main/java/net/skyscanner/backpack/badge/BpkBadge.kt
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_destructive.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_destructiveWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_inverse.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_inverseWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_normal.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_normalWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_outline.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_outlineWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_strong.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_strongWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_successWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_warning.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_warningWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_destructive.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_destructiveWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_inverse.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_inverseWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_normal.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_normalWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_outline.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_outlineWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_strong.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_strongWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_successWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_warning.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_warningWithIcon.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.badge.BpkBadgeTest_default.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.badge.BpkBadgeTest_default.png
Labels: patch

#1872 LMN-1159 Add price row variant
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.ExtraSmall_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.Large_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.Small_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.ExtraSmall_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.Large_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.Small_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.ExtraSmall_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.Large_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.Small_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.ExtraSmall_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.Large_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.Small_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.ExtraSmall_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.Large_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.Small_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.ExtraSmall_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.Large_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.Small_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.ExtraSmall_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.Large_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.Small_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.ExtraSmall_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.Large_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.Small_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.ExtraSmall_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.Large_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceFull.Small_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.ExtraSmall_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.Large_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceLineThroughTrailing.Small_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.ExtraSmall_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.Large_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceOnly.Small_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.ExtraSmall_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.Large_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceTrailing.Small_Row.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/PriceStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/BpkPrice.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceAlignEnd.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceAlignStart.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceRow.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceStyles.kt
  docs/compose/Price/README.md
  docs/compose/Price/screenshots/default.png
  docs/compose/Price/screenshots/default_dm.png
  docs/compose/Price/screenshots/extra-small.png
  docs/compose/Price/screenshots/extra-small_dm.png
  docs/compose/Price/screenshots/large.png
  docs/compose/Price/screenshots/large_dm.png
  docs/compose/Price/screenshots/small.png
  docs/compose/Price/screenshots/small_dm.png
Labels: minor

#1873 Use ubuntu-latest with baseline profile gen
  .github/workflows/_build.yml
Labels: skip-changelog

#1875 Remove shot plugin
  app/build.gradle
  build.gradle
  gradle/libs.versions.toml
Labels: skip-changelog

#1877 Added new NavBarStyle.OnDark
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_collapsedSurfaceContrastNavBar.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedSurfaceContrastNavBar.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedSurfaceContrastNavBar.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.navigationbar.BpkTopNavBarTest_expandedSurfaceContrastNavBar.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/NavBarStory.kt
  app/src/test/java/net/skyscanner/backpack/compose/navigationbar/BpkTopNavBarTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/BpkTopNavBar.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt
  docs/compose/NavBar/README.md
  docs/compose/NavBar/screenshots/surfacecontrast.png
  docs/compose/NavBar/screenshots/surfacecontrast_dm.png
Labels: minor

#1880 RALP-4761 use index from HorizontalPager to select current image
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/imagegallery/internal/BpkImageGallerySlideshow.kt
Labels: patch

#1882 [WASABI-8612] Fix a background shining through in BpkFlightLeg's carrier logo
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.flightleg.BpkFlightLegTest_simpleLegTest.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/FlightLegStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/flightleg/BpkFlightLeg.kt
  docs/compose/FlightLeg/screenshots/default.png
  docs/compose/FlightLeg/screenshots/default_dm.png
Labels: patch
