Repository Skyscanner/backpack-android, pull requests merged in 2024-11, with the labels that each got.

#2128 DON-856 Add configuration for drop down width.
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.select.BpkSelectTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.select.BpkSelectTest_disabled.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlist.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMatchOptionWidth.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMatchSelectWidth.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMaxWidth.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.select.BpkSelectTest_error.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_disabled.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlist.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMatchOptionWidth.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMatchSelectWidth.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMaxWidth.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_error.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.select.BpkSelectTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.select.BpkSelectTest_disabled.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlist.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMatchOptionWidth.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMatchSelectWidth.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMaxWidth.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.select.BpkSelectTest_error.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/SelectStory.kt
  app/src/test/java/net/skyscanner/backpack/compose/select/BpkSelectTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/select/BpkSelect.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/select/internal/BpkSelectImpl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/textfield/internal/BpkTextFieldImpl.kt
  docs/compose/FieldSet/screenshots/default.png
  docs/compose/FieldSet/screenshots/default_dm.png
  docs/compose/FieldSet/screenshots/disabled.png
  docs/compose/FieldSet/screenshots/disabled_dm.png
  docs/compose/FieldSet/screenshots/error.png
  docs/compose/FieldSet/screenshots/error_dm.png
  docs/compose/FieldSet/screenshots/validated.png
  docs/compose/FieldSet/screenshots/validated_dm.png
  docs/compose/Select/README.md
  docs/compose/Select/screenshots/default.png
  docs/compose/Select/screenshots/default_dm.png
  docs/compose/Select/screenshots/matchoptionwidth.png
  docs/compose/Select/screenshots/matchoptionwidth_dm.png
  docs/compose/Select/screenshots/matchselectwidth.png
  docs/compose/Select/screenshots/matchselectwidth_dm.png
  docs/compose/Select/screenshots/maxwidth.png
  docs/compose/Select/screenshots/maxwidth_dm.png
Labels: minor

#2130 [MUON-624] - Expose interactionSource to support custom animations
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/BpkGraphicPromo.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/internal/BpkGraphicPromoImpl.kt
Labels: minor

#2133 nojira remove cross fade from BpkCalendarDayCell
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
Labels: minor

#2141 [MUON-625] Added parameter animationIndicationNode in BpkGraphicPromo to enable customisation of clicking animation
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/BpkGraphicPromo.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/internal/BpkGraphicPromoImpl.kt
Labels: minor, bpk

#2139 don-862 implement segmented control
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceDefaultTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceDefaultTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceDefaultTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceDefaultTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceDefaultTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceDefaultTwoButtons.png
  app/src/main/java/net/skyscanner/backpack/demo/components/SegmentedControlComponent.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/SegmentedControlStory.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/net/skyscanner/backpack/compose/segmentedcontrol/BpkSegmentedControlTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/segmentedcontrol/BpkSegmentedControl.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/segmentedcontrol/internal/BpkSegmentedControlImpl.kt
  docs/compose/SegmentedControl/README.md
  docs/compose/SegmentedControl/screenshots/canvas-contrast.png
  docs/compose/SegmentedControl/screenshots/canvas-contrast_dm.png
  docs/compose/SegmentedControl/screenshots/canvas-default.png
  docs/compose/SegmentedControl/screenshots/canvas-default_dm.png
  docs/compose/SegmentedControl/screenshots/surface-contrast.png
  docs/compose/SegmentedControl/screenshots/surface-contrast_dm.png
  docs/compose/SegmentedControl/screenshots/surface-default.png
  docs/compose/SegmentedControl/screenshots/surface-default_dm.png
  docs/view/TextField/screenshots/with-labels_dm.png
Labels: minor

#2144 Upload demo app to runway
  .github/workflows/release.yml
  README.md
  app/build.gradle
Labels: patch

#2146 [MUON-625] Eliminate duplicated line
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/internal/BpkGraphicPromoImpl.kt
Labels: minor, bpk

#2150 PAN-3440: Add Icon for price component
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.ExtraSmall_End.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.ExtraSmall_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.ExtraSmall_Start.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Large_End.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Large_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Large_Start.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Small_End.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Small_Row.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Small_Start.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.ExtraSmall_End.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.ExtraSmall_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.ExtraSmall_Start.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Large_End.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Large_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Large_Start.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Small_End.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Small_Row.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Small_Start.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.ExtraSmall_End.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.ExtraSmall_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.ExtraSmall_Start.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Large_End.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Large_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Large_Start.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Small_End.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Small_Row.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.price.BpkPriceTest_priceWithIcon.Small_Start.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/PriceStory.kt
  app/src/test/java/net/skyscanner/backpack/compose/price/BpkPriceTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/BpkPrice.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceAlignEnd.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceAlignStart.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceRow.kt
  docs/compose/Price/screenshots/default.png
  docs/compose/Price/screenshots/default_dm.png
Labels: minor, bpk

#2157 [TEMPURA-2060] Contribute to Backpack library Badge icon with Painter
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_customIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.badge.BpkBadgeTest_customIcon.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/BadgeStory.kt
  app/src/test/java/net/skyscanner/backpack/compose/badge/BpkBadgeTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/badge/BpkBadge.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/badge/internal/BpkBadgeImpl.kt
  docs/compose/Badge/README.md
  docs/compose/Badge/screenshots/default.png
  docs/compose/Badge/screenshots/default_dm.png
Labels: minor, bpk

#2159 Fix experimental flag triggering on non-experimental usage
  android-configuration.gradle
  app/src/main/java/net/skyscanner/backpack/demo/compose/StarRatingStory.kt
  app/src/test/java/net/skyscanner/backpack/compose/starrating/BpkStarRatingTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/starrating/BpkStarRating.kt
Labels: patch

#2158 [DON-891] add annotated string to calendar day
  .idea/inspectionProfiles/ktlint.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
Labels: minor, bpk
