Repository Skyscanner/backpack-android, pull requests merged in 2024-01, with the labels that each got.

#1833 Remove jetifier and picasso
  app/build.gradle
  app/src/androidTest/java/net/skyscanner/backpack/dialog/BpkDialogTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/stories/DialogStory.kt
  app/src/main/res/drawable-nodpi/dialog_sample.jpg
  docs/view/Dialog/README.md
  gradle.properties
  gradle/libs.versions.toml
  lint.xml
Labels: skip-changelog

#1834 LMN-1036 Add image gallery carousel
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_carousel.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_carousel.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_carousel.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/imagegallery/BpkImageGalleryTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/components/ImageGalleryComponent.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ImageGalleryStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/carousel/BpkCarousel.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/imagegallery/BpkImageGallery.kt
  docs/compose/ImageGallery/README.md
  docs/compose/ImageGallery/screenshots/carousel.png
  docs/compose/ImageGallery/screenshots/carousel_dm.png
  docs/view/Dialog/screenshots/flare.png
Labels: minor

#1839 LMN-965 Add image gallery slideshow
  app/build.gradle
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow_landscape.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow_second_page.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow_landscape.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow_second_page.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow_landscape.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow_second_page.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/imagegallery/BpkImageGalleryTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/ImageGalleryStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/carousel/BpkCarousel.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/imagegallery/BpkImageGallery.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/imagegallery/BpkImageGalleryCarousel.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/imagegallery/internal/BpkImageGallerySlideshow.kt
  docs/compose/ImageGallery/README.md
  docs/compose/ImageGallery/screenshots/slideshow.png
  docs/compose/ImageGallery/screenshots/slideshow_dm.png
  gradle/libs.versions.toml
Labels: minor

#1844 LMN-843 Add rating bar component
  Backpack/src/main/res/values-night/backpack.internal.color.xml
  Backpack/src/main/res/values/backpack.internal.color.xml
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.ratingbar.BpkRatingBarTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.ratingbar.BpkRatingBarTest_onContrast.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.ratingbar.BpkRatingBarTest_onContrast_zero_to_10.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.ratingbar.BpkRatingBarTest_zero_to_10.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.text.BpkTextTest_hero1.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.text.BpkTextTest_hero2.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.ratingbar.BpkRatingBarTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.ratingbar.BpkRatingBarTest_onContrast.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.ratingbar.BpkRatingBarTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.ratingbar.BpkRatingBarTest_onContrast.png
  app/src/androidTest/java/net/skyscanner/backpack/compose/ratingbar/BpkRatingBarTest.kt
  app/src/main/java/net/skyscanner/backpack/demo/components/RatingBarComponent.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/RatingBarStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/ratingbar/BpkRatingBar.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/internal/BpkRatingBarColors.kt
  docs/compose/RatingBar/README.md
  docs/compose/RatingBar/screenshots/default.png
  docs/compose/RatingBar/screenshots/default_dm.png
  package-lock.json
  package.json
Labels: minor

#1848 Ralp-4728 Update visual appearance of Badges in Compose
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_brand.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_destructive.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_inverse.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_normal.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_outline.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_strong.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_success.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_warning.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.badge.BpkBadgeTest_withIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.barchart.BpkBarchartTest_withLegend.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_past.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_carousel.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow_landscape.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.badge.BpkBadgeTest_brand.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.badge.BpkBadgeTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.badge.BpkBadgeTest_destructive.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.badge.BpkBadgeTest_inverse.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.badge.BpkBadgeTest_normal.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.badge.BpkBadgeTest_outline.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.badge.BpkBadgeTest_strong.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.badge.BpkBadgeTest_success.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.badge.BpkBadgeTest_warning.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.barchart.BpkBarchartTest_withLegend.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_past.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_carousel.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow_landscape.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.badge.BpkBadgeTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.badge.BpkBadgeTest_withIcon.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.barchart.BpkBarchartTest_withLegend.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_carousel.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.imagegallery.BpkImageGalleryTest_slideshow_landscape.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/BadgeStory.kt
  app/src/test/java/net/skyscanner/backpack/compose/badge/BpkBadgeTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/badge/BpkBadge.kt
  docs/compose/Badge/screenshots/default.png
  docs/compose/Badge/screenshots/default_dm.png
  docs/compose/BarChart/screenshots/default.png
  docs/compose/BarChart/screenshots/default_dm.png
  docs/compose/ImageGallery/screenshots/carousel.png
  docs/compose/ImageGallery/screenshots/carousel_dm.png
  docs/compose/ImageGallery/screenshots/slideshow.png
  docs/compose/ImageGallery/screenshots/slideshow_dm.png
  docs/view/Nudger/screenshots/default_dm.png
Labels: patch

#1850 [WASABI-8563] Replace iOS-specific share icon with Android-specific in Jetpack Compose implementation of Share Card Button
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Default_Contained.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Default_Default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Default_OnDark.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Large_Contained.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Large_Default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Large_OnDark.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Default_Contained.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Default_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Default_OnDark.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Large_Contained.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Large_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Large_OnDark.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Default_Contained.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Default_Default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Default_OnDark.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Large_Contained.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Large_Default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardbutton.BpkCardButtonTest_defaultShareButton.Large_OnDark.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/cardbutton/internal/BpkCardButtonImpl.kt
  docs/compose/CardButton/screenshots/default.png
  docs/compose/CardButton/screenshots/default_dm.png
  docs/compose/CardButton/screenshots/large.png
  docs/compose/CardButton/screenshots/large_dm.png
Labels: patch

#1853 [NOJIRA]: Fix BpkHeadlineSkeleton radius and package name
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.skeleton.BpkSkeletonTest_headlineWithCustomHeight.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.skeleton.BpkSkeletonTest_smallHeadline.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.skeleton.BpkSkeletonTest_smallHeadline.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.skeleton.BpkSkeletonTest_smallHeadline.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/SkeletonStory.kt
  app/src/test/java/net/skyscanner/backpack/compose/skeleton/BpkSkeletonTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSearchModalLoading.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/skeleton/BpkSkeleton.kt
  docs/compose/Skeleton/screenshots/default.png
  docs/compose/Skeleton/screenshots/default_dm.png
Labels: major

#1856 Ralp-4729 Update visual appearance of Badges in View
  Backpack/src/main/java/net/skyscanner/backpack/badge/BpkBadge.kt
  Backpack/src/main/res/values/attrs.xml
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_destructive.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_destructiveWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_inverse.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_inverseWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_normal.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_normalWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_outline.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_outlineWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_strong.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_strongWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_success.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_successWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_warning.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.badge.BpkBadgeTest_warningWithIcon.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.barchart.BpkBarchartTests_withLegend.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.calendar.BpkCalendarTest_past.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.calendar.BpkCalendarTest_setSelectionFromTop.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.calendar.BpkCalendarTest_withHighlightedDaysFooter.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_destructive.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_destructiveWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_inverse.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_inverseWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_normal.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_normalWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_outline.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_outlineWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_strong.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_strongWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_success.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_successWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_warning.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.badge.BpkBadgeTest_warningWithIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.barchart.BpkBarchartTests_withLegend.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.calendar.BpkCalendarTest_past.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.calendar.BpkCalendarTest_setSelectionFromTop.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.calendar.BpkCalendarTest_withHighlightedDaysFooter.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.badge.BpkBadgeTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.barchart.BpkBarchartTests_withLegend.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.calendar.BpkCalendarTest_past.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.calendar.BpkCalendarTest_setSelectionFromTop.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.calendar.BpkCalendarTest_withHighlightedDaysFooter.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.badge.BpkBadgeTest_default.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.barchart.BpkBarchartTests_withLegend.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.calendar.BpkCalendarTest_past.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.calendar.BpkCalendarTest_setSelectionFromTop.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.calendar.BpkCalendarTest_withHighlightedDaysFooter.png
  app/src/main/res/layout/fragment_badge.xml
  app/src/main/res/values/strings.xml
  docs/view/Badge/screenshots/default.png
  docs/view/Badge/screenshots/default_dm.png
  docs/view/BarChart/screenshots/default.png
  docs/view/BarChart/screenshots/default_dm.png
  docs/view/Nudger/screenshots/default_dm.png
Labels: patch
