Repository Skyscanner/backpack-android, pull requests merged in 2024-05, with the labels that each got.

#1972 AI-308 origin drop down text overlap
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.button.BpkButtonTest_longTextWithIconAtEnd.Primary_Default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.button.BpkButtonTest_longTextWithIconAtEnd.Primary_Large.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.button.BpkButtonTest_longTextWithIconAtStart.Primary_Default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.button.BpkButtonTest_longTextWithIconAtStart.Primary_Large.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.button.BpkButtonTest_longTextWithIconAtEnd.Primary_Default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.button.BpkButtonTest_longTextWithIconAtEnd.Primary_Large.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.button.BpkButtonTest_longTextWithIconAtStart.Primary_Default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.button.BpkButtonTest_longTextWithIconAtStart.Primary_Large.png
  app/src/test/java/net/skyscanner/backpack/compose/button/BpkButtonTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/BpkButton.kt
Labels: patch

#1984 RALP-4817 Migrate to using Modifier.Node instead of composed
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/barchart/internal/BarChartColumn.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/barchart/internal/BarChartList.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/horizontalnav/BpkHorizontalNav.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/starrating/BpkStarRating.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/ContentDescriptionScope.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/Modifier.kt
Labels: patch

#1988 [NO-JIRA] - Update header button icon, add weight constraint and apply auto formatting
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithButton.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescription.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescriptionAndButton.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDark.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithButton.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescription.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescriptionAndButton.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithButton.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescription.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescriptionAndButton.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDark.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithButton.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescription.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescriptionAndButton.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithButton.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescription.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_defaultWithDescriptionAndButton.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDark.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithButton.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescription.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.sectionheader.BpkSectionHeaderTest_onDarkWithDescriptionAndButton.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/sectionheader/internal/BpkSectionHeaderImpl.kt
  docs/compose/SectionHeader/screenshots/default.png
  docs/compose/SectionHeader/screenshots/default_dm.png
  docs/compose/SectionHeader/screenshots/ondark.png
  docs/compose/SectionHeader/screenshots/ondark_dm.png
Labels: skip-changelog

#1996 RALP-4851 add screenreader focus on disabled switch states
  .gitignore
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/switch/BpkSwitch.kt
Labels: patch

#1986 [MUON-304] - CardList - Rail
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardlist.rail.BpkRailCardListTest_defaultRail.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.cardlist.rail.BpkRailCardListTest_defaultRailWithHeaderButton.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardlist.rail.BpkRailCardListTest_defaultRail.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.cardlist.rail.BpkRailCardListTest_defaultRailWithHeaderButton.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardlist.rail.BpkRailCardListTest_defaultRail.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.cardlist.rail.BpkRailCardListTest_defaultRailWithHeaderButton.png
  app/src/main/java/net/skyscanner/backpack/demo/components/CardListComponent.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/CardListStory.kt
  app/src/main/res/drawable-nodpi/alicante.jpg
  app/src/main/res/drawable-nodpi/amsterdam.jpg
  app/src/main/res/drawable-nodpi/barcelona.jpg
  app/src/main/res/drawable-nodpi/berlin.jpg
  app/src/main/res/drawable-nodpi/dublin.jpg
  app/src/main/res/drawable-nodpi/london_saintpancrasstation.jpg
  app/src/main/res/drawable-nodpi/london_towerbridge.jpg
  app/src/main/res/drawable-nodpi/mallorca.jpg
  app/src/main/res/drawable-nodpi/paris.jpg
  app/src/main/res/values/strings.xml
  app/src/test/java/net/skyscanner/backpack/compose/cardlist/rail/BpkRailCardListTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/cardlist/rail/BpkRailCardList.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/cardlist/rail/internal/BpkRailCardListImpl.kt
  docs/compose/CardList/README.md
  docs/compose/CardList/screenshots/rail-with-headerbutton.png
  docs/compose/CardList/screenshots/rail-with-headerbutton_dm.png
  docs/compose/CardList/screenshots/rail.png
  docs/compose/CardList/screenshots/rail_dm.png
Labels: minor
