Repository Skyscanner/backpack-android, pull requests merged in 2025-01, with the labels that each got.

#2184 Donburi/don 1106 fix background animation segmented control
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceDefaultTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceDefaultTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceDefaultTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceDefaultTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_longValue.SurfaceDefaultTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasContrastTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultFourButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultThreeButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.CanvasDefaultTwoButtonsAndShadow.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceContrastTwoButtons.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.segmentedcontrol.BpkSegmentedControlTest_regularValue.SurfaceDefaultTwoButtons.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/SegmentedControlStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/segmentedcontrol/internal/BpkSegmentedControlImpl.kt
  docs/compose/SegmentedControl/screenshots/canvas-contrast.png
  docs/compose/SegmentedControl/screenshots/canvas-contrast_dm.png
  docs/compose/SegmentedControl/screenshots/canvas-default.png
  docs/compose/SegmentedControl/screenshots/canvas-default_dm.png
  docs/compose/SegmentedControl/screenshots/surface-contrast.png
  docs/compose/SegmentedControl/screenshots/surface-contrast_dm.png
  docs/compose/SegmentedControl/screenshots/surface-default.png
  docs/compose/SegmentedControl/screenshots/surface-default_dm.png
Labels: minor

#2190 [NO JIRA]: Updating foundations to the latest
  Backpack/src/main/res/values/backpack.semantic.color.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColors.kt
  package-lock.json
  package.json
Labels: patch

#2189 Donburi/don 1061 configurable year label
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withYearInMonthLabel.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withYearInMonthLabel.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/CalendarStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/CalendarStoryType.kt
  app/src/test/java/net/skyscanner/backpack/calendar2/BpkCalendarTestCases.kt
  app/src/test/java/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarCellsLayoutTests.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
  backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendar.kt
  docs/compose/Calendar2/README.md
  docs/compose/Calendar2/screenshots/year-in-month-label-no-floating-year.png
  docs/compose/Calendar2/screenshots/year-in-month-label-no-floating-year_dm.png
Labels: minor

#2195 SDPLAT-26630: use GH_APP for GitHub REST API
  .github/workflows/_build.yml
  .github/workflows/label-check.yml
  .github/workflows/pr.yml
Labels: skip-changelog

#2196 SDPLAT-26630: use GH_APP in main.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: skip-changelog

#2197 SDPLAT-26630: use GH App in Release Drafter
  .github/workflows/main.yml
Labels: skip-changelog

#2194 DON-1064 Update BpkCalendar spacing
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_default.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_labeled.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_leapFebruary.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_nonLeapFebruary.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_past.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_todayIsLastDayOfMonth.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_todayIsNewYear.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withDisabledDates.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withDisabledDates_SelectDisabledDate.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withDisabledDates_SelectRange.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withDisabledDates_SelectSingle.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withRangeSet.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withSingleDaySet.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withWholeMonthButtonEnabled.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withWholeMonthSet.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withYearInMonthLabel.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_labeled.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_past.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withDisabledDates.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withRangeSet.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withSingleDaySet.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withWholeMonthButtonEnabled.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withWholeMonthSet.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withYearInMonthLabel.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_default.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withRangeSet.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.calendar.BpkCalendarTest_withWholeMonthButtonEnabled.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
  docs/compose/Calendar2/screenshots/day-icon-as-labels.png
  docs/compose/Calendar2/screenshots/day-icon-as-labels_dm.png
  docs/compose/Calendar2/screenshots/day-labels.png
  docs/compose/Calendar2/screenshots/day-labels_dm.png
  docs/compose/Calendar2/screenshots/pre-selected-range.png
  docs/compose/Calendar2/screenshots/pre-selected-range_dm.png
  docs/compose/Calendar2/screenshots/selection-whole-month.png
  docs/compose/Calendar2/screenshots/selection-whole-month_dm.png
  docs/compose/Calendar2/screenshots/year-in-month-label-no-floating-year.png
  docs/compose/Calendar2/screenshots/year-in-month-label-no-floating-year_dm.png
Labels: patch
