Repository Skyscanner/backpack-android, pull requests merged in 2025-08, with the labels that each got.

#2379 DON-1952: Android Backpack fix additional padding applied to checkbox and radio buttons
  Backpack/src/androidTest/java/net/skyscanner/backpack/checkbox/BpkCheckboxTest.kt
  Backpack/src/androidTest/java/net/skyscanner/backpack/radiobutton/BpkRadioButtonTest.kt
  Backpack/src/main/java/net/skyscanner/backpack/checkbox/BpkCheckbox.kt
  Backpack/src/main/java/net/skyscanner/backpack/radiobutton/BpkRadioButton.kt
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.checkbox.BpkCheckboxTest_noLabel.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.radiobutton.BpkRadioButtonTest_noLabel.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/CheckboxStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/RadioButtonStory.kt
  app/src/main/res/layout/fragment_checkbox.xml
  app/src/main/res/layout/fragment_radio_button.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/net/skyscanner/backpack/checkbox/BpkCheckboxTests.kt
  app/src/test/java/net/skyscanner/backpack/compose/checkbox/BpkCheckboxTest.kt
  app/src/test/java/net/skyscanner/backpack/compose/radiobutton/BpkRadioButtonTest.kt
  app/src/test/java/net/skyscanner/backpack/radiobutton/BpkRadioButtonTests.kt
  docs/compose/Checkbox/screenshots/default.png
  docs/compose/Checkbox/screenshots/default_dm.png
  docs/compose/RadioButton/screenshots/default.png
  docs/compose/RadioButton/screenshots/default_dm.png
  docs/view/Checkbox/screenshots/default.png
  docs/view/Checkbox/screenshots/default_dm.png
  docs/view/RadioButton/screenshots/default.png
  docs/view/RadioButton/screenshots/default_dm.png
Labels: patch

#2380 DON-1923 enable title color and collaspe background color to consumer
  Backpack/src/main/java/net/skyscanner/backpack/navbar/BpkNavBar.kt
  app/src/main/java/net/skyscanner/backpack/demo/stories/NavBarStory.kt
Labels: minor

#2382 [DON-1968] Refactor moved CalendarDayCellTestTag from internal package
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/CalendarDayCellTestTag.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/data/CalendarCell.kt
Labels: patch

#2394 DON-1984 Add Configuration Object
  Backpack/src/main/res/values/backpack.button.xml
  Backpack/tokens.gradle.kts
  backpack-common/build.gradle
  backpack-common/src/main/kotlin/net/skyscanner/backpack/configuration/BpkConfiguration.kt
  backpack-common/src/main/kotlin/net/skyscanner/backpack/util/ExperimentalBackpackApi.kt
  backpack-common/src/main/kotlin/net/skyscanner/backpack/util/InternalBackpackApi.kt
  backpack-common/src/main/res/values-night/backpack.internal.color.xml
  backpack-common/src/main/res/values-night/backpack.semantic.color.xml
  backpack-common/src/main/res/values/backpack.animation.xml
  backpack-common/src/main/res/values/backpack.borders.xml
  backpack-common/src/main/res/values/backpack.color.xml
  backpack-common/src/main/res/values/backpack.dimensions.spacing.xml
  backpack-common/src/main/res/values/backpack.elevation.xml
  backpack-common/src/main/res/values/backpack.internal.color.xml
  backpack-common/src/main/res/values/backpack.radii.xml
  backpack-common/src/main/res/values/backpack.semantic.color.xml
  backpack-common/src/main/res/values/backpack.text.size.xml
  backpack-common/src/main/res/values/backpack.text.xml
  backpack-common/src/main/res/values/colors.xml
  backpack-common/src/test/kotlin/net/skyscanner/backpack/configuration/BpkConfigurationTest.kt
  backpack-common/tokens.gradle.kts
Labels: minor, ai: copilot, ai: jetbrains

#2400 DON-1977 BpkLink Componenet
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.link.BpkLinkTest_linkWithTextStyles.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.link.BpkLinkTest_sentenceWithTwoLinks.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.link.BpkLinkTest_simpleLinkDefault.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.link.BpkLinkTest_simpleLinkOnContrast.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.link.BpkLinkTest_simpleLinkDefault.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.link.BpkLinkTest_simpleLinkOnContrast.png
  app/src/main/java/net/skyscanner/backpack/demo/components/LinkComponent.kt
  app/src/main/java/net/skyscanner/backpack/demo/compose/LinkStory.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/net/skyscanner/backpack/compose/link/BpkLinkTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/link/BpkLink.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/link/TextSegmentBuilder.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/link/internal/BpkLinkImpl.kt
  docs/compose/Link/README.md
  docs/compose/Link/screenshots/default.png
  docs/compose/Link/screenshots/default_dm.png
  docs/compose/Link/screenshots/oncontrast.png
  docs/compose/Link/screenshots/oncontrast_dm.png
Labels: minor, ai: jetbrains
