Repository Skyscanner/backpack-android, pull requests merged in 2025-05, with the labels that each got.

#2278 DON-1469 Tweak animations
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/skeleton/BpkSkeleton.kt
Labels: patch

#2282 Fixed deprecated code for months in backpack
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarMonth.kt
Labels: patch

#2283 DON-1469 Tweak animations
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/skeleton/BpkSkeleton.kt
Labels: patch

#2284 [SONIC-3515] Minor fixes in BpkSwitch
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/oss/debug/default/net.skyscanner.backpack.compose.switch.BpkSwitchTest_disabledUnchecked.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.switch.BpkSwitchTest_disabledUnchecked.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.compose.switch.BpkSwitchTest_defaultUnchecked.png
  app/src/main/java/net/skyscanner/backpack/demo/compose/SwitchStory.kt
  app/src/main/res/values/strings.xml
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/switch/BpkSwitch.kt
Labels: minor

#2289 fix bpkswitch when content is empty
  app/src/main/java/net/skyscanner/backpack/demo/compose/SwitchStory.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/switch/BpkSwitch.kt
  docs/compose/Switch/README.md
Labels: minor

#2290 [DON-1385] change selection mode single to support dynamic accessbility
  app/src/main/java/net/skyscanner/backpack/demo/data/CalendarStoryType.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarAccessibilityLabelTests.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarDayCellTestTag.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarCell.kt
  backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
  docs/compose/Calendar2/README.md
Labels: minor

#2296 Revert "[DON-1385] change selection mode single to support dynamic accessbility"
  app/src/main/java/net/skyscanner/backpack/demo/data/CalendarStoryType.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarAccessibilityLabelTests.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarCell.kt
  backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarDayCellTestTag.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
  docs/compose/Calendar2/README.md
Labels: patch

#2297 DON-1625 Update view based text field hint colour
  Backpack/src/main/java/net/skyscanner/backpack/text/BpkTextField.kt
  app/screenshots/oss/debug/default/net.skyscanner.backpack.text.BpkTextFieldTests_hint.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.text.BpkTextFieldTests_hint.png
  app/screenshots/oss/debug/rtl/net.skyscanner.backpack.text.BpkTextFieldTests_hint.png
  docs/view/TextField/screenshots/default.png
  docs/view/TextField/screenshots/default_dm.png
  docs/view/TextField/screenshots/with-labels.png
  docs/view/TextField/screenshots/with-labels_dm.png
Labels: patch

#2298 DON-1385 selection mode changes to support dynamic accessbility label
  app/src/main/java/net/skyscanner/backpack/demo/data/CalendarStoryType.kt
  backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarAccessibilityLabelTests.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarDayCellTestTag.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarCell.kt
  backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
  docs/compose/Calendar2/README.md
Labels: major

#2299 Updated references and tokens
  Backpack/src/androidTest/java/net/skyscanner/backpack/spinner/BpkSpinnerTest.kt
  Backpack/src/main/java/net/skyscanner/backpack/badge/BpkBadge.kt
  Backpack/src/main/java/net/skyscanner/backpack/horisontalnav/BpkHorizontalNav.kt
  Backpack/src/main/java/net/skyscanner/backpack/spinner/BpkSpinner.kt
  Backpack/src/main/res/drawable/bpk_horizontal_nav_dot.xml
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.barchart.BpkBarchartTests_default.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.barchart.BpkBarchartTests_fullyFilled.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.barchart.BpkBarchartTests_inactive.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.barchart.BpkBarchartTests_withLegend.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.starrating.BpkInteractiveStarRatingTest_default.png
  app/screenshots/oss/debug/themed/net.skyscanner.backpack.starrating.BpkStarRatingTest_default.png
  app/src/main/res/values/themes.xml
  docs/compose/Calendar2/screenshots/highlighted-dates.png
  docs/compose/Calendar2/screenshots/highlighted-dates_dm.png
  docs/compose/CardList/screenshots/stack---column-based.png
  docs/compose/CardList/screenshots/stack---column-based_dm.png
  docs/compose/CardList/screenshots/stack---lazy-column-based.png
  docs/compose/CardList/screenshots/stack---lazy-column-based_dm.png
  docs/compose/CardList/screenshots/stack-with-button-accessory---column-based.png
  docs/compose/CardList/screenshots/stack-with-button-accessory---column-based_dm.png
  docs/compose/CardList/screenshots/stack-with-button-accessory---lazy-column-based.png
  docs/compose/CardList/screenshots/stack-with-button-accessory---lazy-column-based_dm.png
  docs/compose/CardList/screenshots/stack-with-button-accessory-and-headerbutton---column-based.png
  docs/compose/CardList/screenshots/stack-with-button-accessory-and-headerbutton---column-based_dm.png
  docs/compose/CardList/screenshots/stack-with-button-accessory-and-headerbutton---lazy-column-based.png
  docs/compose/CardList/screenshots/stack-with-button-accessory-and-headerbutton---lazy-column-based_dm.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory---column-based.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory---column-based_dm.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory---lazy-column-based.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory---lazy-column-based_dm.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory-and-expandedcount-less-than-minimum---column-based.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory-and-expandedcount-less-than-minimum---column-based_dm.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory-and-expandedcount-less-than-minimum---lazy-column-based.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory-and-expandedcount-less-than-minimum---lazy-column-based_dm.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory-and-headerbutton---column-based.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory-and-headerbutton---column-based_dm.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory-and-headerbutton---lazy-column-based.png
  docs/compose/CardList/screenshots/stack-with-expand-accessory-and-headerbutton---lazy-column-based_dm.png
  docs/compose/Carousel/screenshots/default.png
  docs/compose/Carousel/screenshots/default_dm.png
  docs/view/Dialog/screenshots/flare_dm.png
  docs/view/HorizontalNav/screenshots/default.png
  docs/view/HorizontalNav/screenshots/default_dm.png
  docs/view/Nudger/screenshots/default.png
  docs/view/Nudger/screenshots/default_dm.png
  docs/view/TextField/screenshots/with-labels_dm.png
  gradle.properties
Labels: patch, bpk

#2300 -am migrate missing deprecated token
  app/src/main/res/values/themes.xml
Labels: minor

#2310 INL-3110 revert back compose bom version
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_imageModelDark.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.bottomsheet.BpkBottomSheetTest_imageModelDarkWithTopBar.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_disabled.Destructive_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_disabled.Featured_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_disabled.Link_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_disabled.Primary_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_disabled.Secondary_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_loading.Destructive_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_loading.Featured_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_loading.Link_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_loading.Primary_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_loading.Primary_Large.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_loading.Secondary_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_text.Destructive_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_text.Featured_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_text.Link_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_text.Primary_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_text.Primary_Large.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.button.BpkButtonTest_text.Secondary_Default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_destructive.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_flare.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_flareVertical.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageEndAlignment.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageStartAlignment.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_imageVertical.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_noIcon.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_successOneButton.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_successThreeButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_successTwoButtons.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.dialog.BpkDialogTest_warning.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.navigationtabgroup.BpkNavigationTabGroupTest_default.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMatchOptionWidth.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMatchSelectWidth.png
  app/screenshots/oss/debug/dm/net.skyscanner.backpack.compose.select.BpkSelectTest_dropdownlistMaxWidth.png
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/floatingnotification/BpkFloatingNotification.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/modal/BpkModal.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/DeviceUtil.kt
  docs/compose/Card/screenshots/divided-card.png
  docs/view/Dialog/screenshots/destructive.png
  docs/view/Dialog/screenshots/destructive_dm.png
  docs/view/Dialog/screenshots/flare_dm.png
  docs/view/FloatingActionButton/screenshots/default.png
  docs/view/Nudger/screenshots/default.png
  docs/view/Nudger/screenshots/default_dm.png
  docs/view/Rating/screenshots/horizontal.png
  docs/view/Rating/screenshots/horizontal_dm.png
  docs/view/Rating/screenshots/pill.png
  docs/view/Rating/screenshots/pill_dm.png
  docs/view/Rating/screenshots/vertical.png
  docs/view/Rating/screenshots/vertical_dm.png
  docs/view/Snackbar/screenshots/icon.png
  docs/view/Snackbar/screenshots/icon_dm.png
  docs/view/StarRating/screenshots/default.png
  docs/view/StarRating/screenshots/default_dm.png
  gradle/libs.versions.toml
Labels: minor

#2312 DON-1626 Create custom navBarActionContentDescription
  Backpack/src/main/java/net/skyscanner/backpack/navbar/BpkNavBar.kt
  Backpack/src/main/res/values/attrs.xml
Labels: minor
