Repository Skyscanner/backpack-android, pull requests merged in 2025-09, with the labels that each got.

#2406 DON-2026 Add logger callback to BpkConfiguration
  backpack-common/src/androidTest/AndroidManifest.xml
  backpack-common/src/androidTest/kotlin/net/skyscanner/backpack/configuration/EmptyActivity.kt
  backpack-common/src/androidTest/kotlin/net/skyscanner/backpack/configuration/ViewUtilsTest.kt
  backpack-common/src/androidTest/res/values/attrs.xml
  backpack-common/src/androidTest/res/values/theme.xml
  backpack-common/src/main/kotlin/net/skyscanner/backpack/configuration/BpkConfiguration.kt
  backpack-common/src/main/kotlin/net/skyscanner/backpack/util/ViewUtils.kt
  backpack-common/src/main/res/values/attrs.xml
  backpack-common/src/test/kotlin/net/skyscanner/backpack/configuration/BpkConfigurationTest.kt
Labels: minor, ai: copilot, ai: jetbrains

#2418 Revert "Bump com.google.maps.android:maps-compose from 6.7.2 to 6.8.0"
  Backpack/lint-baseline.xml
  Backpack/src/main/java/net/skyscanner/backpack/bottomnav/BpkBottomNav.kt
  Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/BpkDialogImpl.kt
  Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/DialogWindowLayout.kt
  Backpack/src/main/java/net/skyscanner/backpack/flare/BpkFlare.kt
  Backpack/src/main/java/net/skyscanner/backpack/navbar/internal/BpkCollapsingToolbarLayout.kt
  Backpack/src/main/java/net/skyscanner/backpack/navbar/internal/BpkToolbar.kt
  Backpack/src/main/java/net/skyscanner/backpack/panel/BpkPanel.kt
  Backpack/src/main/java/net/skyscanner/backpack/snackbar/internal/SnackbarCustomisationUtils.kt
  Backpack/src/main/java/net/skyscanner/backpack/text/BpkText.kt
  Backpack/src/main/java/net/skyscanner/backpack/util/Drawables.kt
  Backpack/src/main/java/net/skyscanner/backpack/util/Views.kt
  android-configuration.gradle
  app/lint-baseline.xml
  app/src/main/java/net/skyscanner/backpack/demo/stories/IconsStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/SettingsThemeOption.kt
  gradle/libs.versions.toml
Labels: patch

#2433 Donburi/don 1954 fix bump gradle agp
  Backpack/build.gradle
  Backpack/build.gradle.kts
  Backpack/src/main/java/net/skyscanner/backpack/bottomnav/BpkBottomNav.kt
  Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/BpkDialogImpl.kt
  Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/DialogWindowLayout.kt
  Backpack/src/main/java/net/skyscanner/backpack/flare/BpkFlare.kt
  Backpack/src/main/java/net/skyscanner/backpack/navbar/internal/BpkCollapsingToolbarLayout.kt
  Backpack/src/main/java/net/skyscanner/backpack/navbar/internal/BpkToolbar.kt
  Backpack/src/main/java/net/skyscanner/backpack/panel/BpkPanel.kt
  Backpack/src/main/java/net/skyscanner/backpack/snackbar/internal/SnackbarCustomisationUtils.kt
  Backpack/src/main/java/net/skyscanner/backpack/text/BpkText.kt
  Backpack/src/main/java/net/skyscanner/backpack/util/Drawables.kt
  Backpack/src/main/java/net/skyscanner/backpack/util/Views.kt
  Backpack/tokens.gradle.kts
  app/src/main/java/net/skyscanner/backpack/demo/data/SharedPreferences.kt
  app/src/main/java/net/skyscanner/backpack/demo/stories/IconsStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/ui/SettingsThemeOption.kt
  backpack-common/build.gradle
  backpack-common/build.gradle.kts
  backpack-common/tokens.gradle.kts
  backpack-compose/build.gradle
  backpack-compose/build.gradle.kts
  backpack-compose/tokens.gradle.kts
  backpack-lint/build.gradle.kts
  backpack-lint/tokens.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: minor
