Repository Skyscanner/backpack-android, pull requests merged in 2025-02, with the labels that each got.

#2209 Revert "Bump org.jetbrains.dokka:dokka-gradle-plugin from 1.9.20 to 2.0.0"
  gradle/libs.versions.toml
Labels: skip-changelog

#2211 [NO JIRA]: Fix commit automations for CI
  .github/workflows/_build.yml
Labels: skip-changelog

#2219 ralp/no-jira Add workaround hanging Android Tests
  .github/workflows/_build.yml
Labels: skip-changelog

#2218 donburi/don-1140_drop_state_flow_from_bpkcalendar
  app/src/main/java/net/skyscanner/backpack/demo/compose/CalendarStory.kt
  app/src/main/java/net/skyscanner/backpack/demo/data/CalendarStoryType.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarState.kt
  backpack-common/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarStateMachine.kt
  backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendar.kt
  backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarController.kt
  docs/compose/Calendar2/README.md
Labels: major

#2220 Update release.yml to align with other Backpack repos
  .github/workflows/release.yml
Labels: patch
